/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import Model.KhachHang;
import Service.KhachHangService;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author admin
 */
public class JPanelKhachHang extends javax.swing.JPanel {

    KhachHangService khS = new KhachHangService();
    List<KhachHang> list = new ArrayList<>();
    int index = 0;
    private static final Pattern DATE_PATTERN = Pattern.compile("^((2000|2400|2800|(19|2[0-9])(0[48]|[2468][048]|[13579][26]))-02-29)$"
            + "|^(((19|2[0-9])[0-9]{2})-02-(0[1-9]|1[0-9]|2[0-8]))$"
            + "|^(((19|2[0-9])[0-9]{2})-(0[13578]|10|12)-(0[1-9]|[12][0-9]|3[01]))$"
            + "|^(((19|2[0-9])[0-9]{2})-(0[469]|11)-(0[1-9]|[12][0-9]|30))$");

    public JPanelKhachHang() {
        initComponents();
        loadTBV();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        txt_ma = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        txt_ten = new javax.swing.JTextField();
        txt_ngaysinh = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        rdo_nam = new javax.swing.JRadioButton();
        rdo_nu = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        txt_sdt = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        txt_timkiem = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_khachhang = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        btn_them = new javax.swing.JButton();
        btn_sua = new javax.swing.JButton();
        btn_xoa = new javax.swing.JButton();
        btn_lammoi = new javax.swing.JButton();
        btn_first = new javax.swing.JButton();
        btn_predious = new javax.swing.JButton();
        btn_next = new javax.swing.JButton();
        btn_last = new javax.swing.JButton();
        chk_trangthai = new javax.swing.JCheckBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_diachi = new javax.swing.JTextArea();
        jLabel30 = new javax.swing.JLabel();
        txt_ngayTao = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel31 = new javax.swing.JLabel();
        txt_ngayNhap = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1070, 680));
        setPreferredSize(new java.awt.Dimension(1070, 680));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel22.setText("Mã khách hàng:");
        jPanel3.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 19, -1, -1));

        txt_ma.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_ma.setBorder(null);
        txt_ma.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel3.add(txt_ma, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 174, -1));

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel25.setText("Tên khách hàng");
        jPanel3.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        txt_ten.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_ten.setBorder(null);
        jPanel3.add(txt_ten, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 174, -1));

        txt_ngaysinh.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_ngaysinh.setBorder(null);
        jPanel3.add(txt_ngaysinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 174, -1));

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel26.setText("Ngày sinh");
        jPanel3.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jLabel27.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel27.setText("Giới Tính");
        jPanel3.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        rdo_nam.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rdo_nam);
        rdo_nam.setSelected(true);
        rdo_nam.setText("Nam");
        jPanel3.add(rdo_nam, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 67, -1));

        rdo_nu.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rdo_nu);
        rdo_nu.setText("Nữ");
        jPanel3.add(rdo_nu, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 67, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Số điện thoại");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, -1, -1));

        txt_sdt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_sdt.setBorder(null);
        jPanel3.add(txt_sdt, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, 174, -1));

        jLabel28.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel28.setText("Địa chỉ");
        jPanel3.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, -1, -1));

        txt_timkiem.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_timkiem.setBorder(null);
        txt_timkiem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_timkiemKeyPressed(evt);
            }
        });
        jPanel3.add(txt_timkiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 40, 174, -1));

        jLabel29.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel29.setText("Tìm kiếm");
        jPanel3.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(739, 19, -1, -1));

        tbl_khachhang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Ma", "Ten", "NgaySinh", "GioiTinh", "Sdt", "DiaChi", "TrangThai"
            }
        ));
        tbl_khachhang.setFocusable(false);
        tbl_khachhang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_khachhangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_khachhang);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 1030, 207));

        jSeparator1.setForeground(new java.awt.Color(186, 79, 84));
        jPanel3.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 174, 12));

        jSeparator2.setForeground(new java.awt.Color(186, 79, 84));
        jPanel3.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 174, 12));

        jSeparator3.setForeground(new java.awt.Color(186, 79, 84));
        jPanel3.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 174, 10));

        jSeparator4.setForeground(new java.awt.Color(186, 79, 84));
        jPanel3.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, 174, 10));

        jSeparator6.setForeground(new java.awt.Color(186, 79, 84));
        jPanel3.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 60, 174, 10));

        btn_them.setBackground(new java.awt.Color(186, 79, 84));
        btn_them.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_them.setForeground(new java.awt.Color(255, 255, 255));
        btn_them.setText("Thêm");
        btn_them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themActionPerformed(evt);
            }
        });
        jPanel3.add(btn_them, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 540, 90, 32));

        btn_sua.setBackground(new java.awt.Color(186, 79, 84));
        btn_sua.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_sua.setForeground(new java.awt.Color(255, 255, 255));
        btn_sua.setText("Sửa");
        btn_sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_suaActionPerformed(evt);
            }
        });
        jPanel3.add(btn_sua, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 540, 87, 32));

        btn_xoa.setBackground(new java.awt.Color(186, 79, 84));
        btn_xoa.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_xoa.setForeground(new java.awt.Color(255, 255, 255));
        btn_xoa.setText("Xóa");
        btn_xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoaActionPerformed(evt);
            }
        });
        jPanel3.add(btn_xoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 540, 87, 32));

        btn_lammoi.setBackground(new java.awt.Color(186, 79, 84));
        btn_lammoi.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_lammoi.setForeground(new java.awt.Color(255, 255, 255));
        btn_lammoi.setText("Mới");
        btn_lammoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_lammoiActionPerformed(evt);
            }
        });
        jPanel3.add(btn_lammoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 540, 87, 32));

        btn_first.setBackground(new java.awt.Color(186, 79, 84));
        btn_first.setText("<<");
        btn_first.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_firstActionPerformed(evt);
            }
        });
        jPanel3.add(btn_first, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 540, 50, 30));

        btn_predious.setBackground(new java.awt.Color(186, 79, 84));
        btn_predious.setText("<");
        btn_predious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_prediousActionPerformed(evt);
            }
        });
        jPanel3.add(btn_predious, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 540, 40, 30));

        btn_next.setBackground(new java.awt.Color(186, 79, 84));
        btn_next.setText(">");
        btn_next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nextActionPerformed(evt);
            }
        });
        jPanel3.add(btn_next, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 540, 40, 30));

        btn_last.setBackground(new java.awt.Color(186, 79, 84));
        btn_last.setText(">>");
        btn_last.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_lastActionPerformed(evt);
            }
        });
        jPanel3.add(btn_last, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 540, 50, 30));

        chk_trangthai.setText("Trạng thái");
        jPanel3.add(chk_trangthai, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 40, -1, -1));

        txt_diachi.setColumns(20);
        txt_diachi.setRows(5);
        jScrollPane2.setViewportView(txt_diachi);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, -1, 70));

        jLabel30.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel30.setText("Ngày Tạo");
        jPanel3.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, -1, -1));

        txt_ngayTao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_ngayTao.setBorder(null);
        jPanel3.add(txt_ngayTao, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 174, -1));

        jSeparator5.setForeground(new java.awt.Color(186, 79, 84));
        jPanel3.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, 174, 10));

        jLabel31.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel31.setText("Ngày Nhập");
        jPanel3.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, -1, -1));

        txt_ngayNhap.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_ngayNhap.setBorder(null);
        jPanel3.add(txt_ngayNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, 174, -1));

        jSeparator7.setForeground(new java.awt.Color(186, 79, 84));
        jPanel3.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, 174, 10));

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, -1, 618));

        jPanel1.setBackground(new java.awt.Color(186, 79, 84));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("          Khách Hàng");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 1070, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 60));
    }// </editor-fold>//GEN-END:initComponents

    private void btn_themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themActionPerformed
        addKH();
    }//GEN-LAST:event_btn_themActionPerformed

    private void btn_suaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_suaActionPerformed
        updateKH();
    }//GEN-LAST:event_btn_suaActionPerformed

    private void btn_xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoaActionPerformed
        if (txt_ma.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập mã để xóa");
            return;
        }
        int cf = JOptionPane.showConfirmDialog(this, "Bạn có muốn xóa không?", "Xóa", JOptionPane.YES_NO_OPTION);
        if (cf == JOptionPane.YES_OPTION) {
            deleteKH();
        }
    }//GEN-LAST:event_btn_xoaActionPerformed

    private void btn_lammoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lammoiActionPerformed
        txt_ma.setText("");
        txt_ten.setText("");
        txt_sdt.setText("");
        txt_diachi.setText("");
        txt_ngayNhap.setText("");
        txt_ngayTao.setText("");
        txt_ngaysinh.setText("");
        rdo_nam.setSelected(true);
        chk_trangthai.setSelected(false);
    }//GEN-LAST:event_btn_lammoiActionPerformed

    private void btn_firstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_firstActionPerformed
//        fillTable(khachHangService.getListKhachHang());
//        if (!khachHangService.getListKhachHang().isEmpty()) {
//            index = 0;
//        }
//        fillField(index);
    }//GEN-LAST:event_btn_firstActionPerformed

    private void btn_prediousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_prediousActionPerformed
//        fillTable(khachHangService.getListKhachHang());
//        if (!khachHangService.getListKhachHang().isEmpty()) {
//            if (index == 0) {
//                index = khachHangService.getListKhachHang().size() - 1;
//            } else {
//                index--;
//            }
//        }
//        fillField(index);
    }//GEN-LAST:event_btn_prediousActionPerformed

    private void btn_nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nextActionPerformed
//        fillTable(khachHangService.getListKhachHang());
//        if (!khachHangService.getListKhachHang().isEmpty()) {
//            if (index == khachHangService.getListKhachHang().size() - 1) {
//                index = 0;
//            } else {
//                index++;
//            }
//        }
//        fillField(index);
    }//GEN-LAST:event_btn_nextActionPerformed

    private void btn_lastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lastActionPerformed
//        fillTable(khachHangService.getListKhachHang());
//        if (!khachHangService.getListKhachHang().isEmpty()) {
//            index = khachHangService.getListKhachHang().size() - 1;
//        }
//        fillField(index);
    }//GEN-LAST:event_btn_lastActionPerformed

    private void tbl_khachhangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_khachhangMouseClicked
        int a = tbl_khachhang.getSelectedRow();

        txt_ma.setText(tbl_khachhang.getValueAt(a, 1).toString());
        txt_ten.setText(tbl_khachhang.getValueAt(a, 2).toString());
        txt_ngaysinh.setText(tbl_khachhang.getValueAt(a, 3).toString());
        txt_sdt.setText(tbl_khachhang.getValueAt(a, 5).toString());
        txt_diachi.setText(tbl_khachhang.getValueAt(a, 6).toString());
        if (tbl_khachhang.getValueAt(a, 4).toString().equalsIgnoreCase("Nam")) {
            rdo_nam.setSelected(true);
        } else {
            rdo_nu.setSelected(true);
        }

        if (tbl_khachhang.getValueAt(a, 7).toString().equalsIgnoreCase("Còn")) {
            chk_trangthai.setSelected(true);
        } else {
            chk_trangthai.setSelected(false);
        }
    }//GEN-LAST:event_tbl_khachhangMouseClicked

    private void txt_timkiemKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_timkiemKeyPressed
//        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
//            if (txt_timkiem.getText().isEmpty()) {
//                fillTable(khachHangService.getListKhachHang());
//            }
//            fillTable(khachHangService.getListKHByMa(txt_timkiem.getText()));
//        }
    }//GEN-LAST:event_txt_timkiemKeyPressed
    private void loadTBV() {
        list = khS.getListDB();
        DefaultTableModel mol = (DefaultTableModel) tbl_khachhang.getModel();
        mol.setRowCount(0);
        for (KhachHang kh : list) {
            mol.addRow(new Object[]{kh.getId(), kh.getMa(), kh.getTen(), kh.getNgaySinh(), kh.getGioiTinh(),
                kh.getSdt(), kh.getDiaChi(), kh.getTrangThai()});
        }
        tbl_khachhang.setModel(mol);
        if (tbl_khachhang.getRowCount() > 0) {
            mouseClickTBV(0);
            tbl_khachhang.setRowSelectionInterval(0, 0);
        }
    }

    private void addKH() {
        String ma = txt_ma.getText().trim();
        String ten = txt_ten.getText().trim();
        String ngaySinh = txt_ngaysinh.getText();
        String gt;
        if (rdo_nam.isSelected() == true) {
            gt = "nam";
        } else {
            gt = "nữ";
        }
        String ngayTao = txt_ngayTao.getText().trim();
        String ngaySua = txt_ngayNhap.getText().trim();
        String sdt = txt_sdt.getText();
        String diaChi = txt_diachi.getText();
        int tt = chk_trangthai.isSelected() ? 0 : 1;
        KhachHang kh = new KhachHang(0, ma, ten, ngaySinh, gt, sdt, diaChi, ngayTao, ngaySua, tt);
        KhachHang vCheck = khS.getDB(ma);
        if (vCheck != null) {
            JOptionPane.showMessageDialog(this, "Mã khách hàng đã tồn tại");
        } else {
            boolean result = khS.create(kh);
            if (result == true) {
                JOptionPane.showMessageDialog(this, "Thêm thành công");
                loadTBV();
            } else {
                JOptionPane.showMessageDialog(this, "Thêm thất bại");
            }
        }
    }

    private void updateKH() {
        int index = tbl_khachhang.getSelectedRow();
        list = khS.getListDB();
        KhachHang kh = list.get(index);
        String ma = txt_ma.getText();
        String ten = txt_ten.getText();
        String ngaySinh = txt_ngaysinh.getText();
        String gt;
        if (rdo_nam.isSelected() == true) {
            gt = "nam";
        } else {
            gt = "nữ";
        }
        String sdt = txt_sdt.getText();
        String diaChi = txt_diachi.getText();
        KhachHang vCheck = khS.getDB(ma);
        if (vCheck == null) {
            kh = new KhachHang(kh.getId(), ma, ten, ngaySinh, gt, sdt, diaChi, null, null, kh.getTrangThai());
            boolean result = khS.update(kh);
            JOptionPane.showMessageDialog(this, "Cập nhật thành công");
            loadTBV();
        } else if (kh.getMa().equals(ma)) {
            kh = new KhachHang(kh.getId(), ma, ten, ngaySinh, gt, sdt, diaChi, null, null, kh.getTrangThai());
            boolean result = khS.update(kh);
            JOptionPane.showMessageDialog(this, "Cập nhật thành công");
            loadTBV();
        } else {
            JOptionPane.showMessageDialog(this, "Mã hãng đã tồn tại");
        }
    }

    private void deleteKH() {
        int index = tbl_khachhang.getSelectedRow();
        KhachHang kh = list.get(index);
        boolean result = khS.delete(kh);
        if (result == true) {
            JOptionPane.showMessageDialog(this, "Xóa thành công");
            loadTBV();
        } else {
            JOptionPane.showMessageDialog(this, "Xóa thất bại");
        }
    }

    private void mouseClickTBV(int index) {
        list = khS.getListDB();
        KhachHang kh = list.get(index);
        txt_ma.setText(kh.getMa());
        txt_ten.setText(kh.getTen());
        txt_sdt.setText(kh.getSdt());
        txt_diachi.setText(kh.getDiaChi());
        if (kh.getGioiTinh().equalsIgnoreCase("Nam")) {
            rdo_nam.setSelected(true);
            return;
        } else {
            rdo_nu.setSelected(true);
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_first;
    private javax.swing.JButton btn_lammoi;
    private javax.swing.JButton btn_last;
    private javax.swing.JButton btn_next;
    private javax.swing.JButton btn_predious;
    private javax.swing.JButton btn_sua;
    private javax.swing.JButton btn_them;
    private javax.swing.JButton btn_xoa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox chk_trangthai;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JRadioButton rdo_nam;
    private javax.swing.JRadioButton rdo_nu;
    private javax.swing.JTable tbl_khachhang;
    private javax.swing.JTextArea txt_diachi;
    private javax.swing.JTextField txt_ma;
    private javax.swing.JTextField txt_ngayNhap;
    private javax.swing.JTextField txt_ngayTao;
    private javax.swing.JTextField txt_ngaysinh;
    private javax.swing.JTextField txt_sdt;
    private javax.swing.JTextField txt_ten;
    private javax.swing.JTextField txt_timkiem;
    // End of variables declaration//GEN-END:variables
}
