package View;

//import com.lowagie.text.Document;
//import com.lowagie.text.DocumentException;
//import com.lowagie.text.Phrase;
//import com.lowagie.text.pdf.PdfPCell;
//import com.lowagie.text.pdf.PdfPTable;
//import com.lowagie.text.pdf.PdfWriter;
//import domainmodel.ChiTietHoaDon;
//import domainmodel.HoaDon;
//import domainmodel.KhachHang;
import Model.KhuyenMai;
//import domainmodel.SanPham;
import java.awt.Color;
import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import static javax.swing.WindowConstants.HIDE_ON_CLOSE;
import javax.swing.table.DefaultTableModel;
//import service.BanHangService;
//import service.HoaDonService;
//import service.NhanVienService;
//import service.SanPhamService;
//import viewmodel.GioHang;

/**
 *
 * @author quyen
 */
public class JPanelBanHang extends javax.swing.JPanel {

//    DefaultTableModel defaultTableModelHoaDon;
//    DefaultTableModel defaultTableModelGioHang;
//    DefaultTableModel defaultTableModelSanPham;
//    HoaDonService hoaDonService = new HoaDonService();
//    SanPhamService sanPhamService = new SanPhamService();
//    BanHangService banHangService = new BanHangService();
//    NhanVienService nhanVienService = new NhanVienService();
//    List<GioHang> listGioHang = new ArrayList<>();

    public JPanelBanHang() {
        initComponents();
//        fillHoaDon(hoaDonService.getListHoaDon());
//        fillSanPham(sanPhamService.getListSP());
//        List<KhachHang> list = banHangService.getListNameKH();
//        cbo_khachhang.setModel(new DefaultComboBoxModel(list.toArray()));
//        List<KhuyenMai> listKM = banHangService.getListGiaTri();
//        cbo_khuyenmai.setModel(new DefaultComboBoxModel(listKM.toArray()));
    }

    public JPanelBanHang(String ten) {
        initComponents();
        txt_tennhanvien.setText(ten);
//        fillHoaDon(hoaDonService.getListHoaDon());
//        fillSanPham(sanPhamService.getListSP());
//        List<KhachHang> list = banHangService.getListNameKH();
//        cbo_khachhang.setModel(new DefaultComboBoxModel(list.toArray()));
//        List<KhuyenMai> listKM = banHangService.getListGiaTri();
//        cbo_khuyenmai.setModel(new DefaultComboBoxModel(listKM.toArray()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txt_timkiem = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_giohang = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_hoadon = new javax.swing.JTable();
        btn_hoadon = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbl_sanpham = new javax.swing.JTable();
        btn_themgiohang = new javax.swing.JButton();
        btn_capnhatgio = new javax.swing.JButton();
        rdo_tatca = new javax.swing.JRadioButton();
        rdo_dathanhtoan = new javax.swing.JRadioButton();
        rdo_chuathanhtoan = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt_tongtien = new javax.swing.JLabel();
        txt_giamgia = new javax.swing.JLabel();
        txt_ngaytao = new javax.swing.JTextField();
        btn_thanhtoan = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        cbo_khachhang = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        cbo_khuyenmai = new javax.swing.JComboBox<>();
        btn_lammoi = new javax.swing.JButton();
        txt_tienphaitra = new javax.swing.JTextField();
        txt_tennhanvien = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1070, 680));
        setPreferredSize(new java.awt.Dimension(1070, 680));

        jLabel2.setBackground(new java.awt.Color(186, 79, 84));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("          Bán Hàng");
        jLabel2.setOpaque(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1070, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_timkiem.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txt_timkiem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_timkiemKeyPressed(evt);
            }
        });
        jPanel2.add(txt_timkiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 200, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Tìm kiếm sản phẩm");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        tbl_giohang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Stt", "Id sản phẩm", "Mã sản phẩm", "Tên sản phẩm", "Số lượng", "Đơn Giá", "Thành Tiền"
            }
        ));
        jScrollPane2.setViewportView(tbl_giohang);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 590, 160));

        tbl_hoadon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Mã", "Ngày Tạo", "Ngày Thanh Toán", "Trạng Thái"
            }
        ));
        tbl_hoadon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_hoadonMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbl_hoadon);

        jPanel2.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 477, 170));

        btn_hoadon.setBackground(new java.awt.Color(186, 79, 84));
        btn_hoadon.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_hoadon.setForeground(new java.awt.Color(255, 255, 255));
        btn_hoadon.setText("Tạo hóa đơn");
        btn_hoadon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hoadonActionPerformed(evt);
            }
        });
        jPanel2.add(btn_hoadon, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 490, -1, 33));

        tbl_sanpham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Stt", "Id", "Mã", "Tên", "Giá bán", "Số lượng"
            }
        ));
        jScrollPane4.setViewportView(tbl_sanpham);

        jPanel2.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 590, 160));

        btn_themgiohang.setBackground(new java.awt.Color(186, 79, 84));
        btn_themgiohang.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_themgiohang.setForeground(new java.awt.Color(255, 255, 255));
        btn_themgiohang.setText("Thêm vào giỏ");
        btn_themgiohang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themgiohangActionPerformed(evt);
            }
        });
        jPanel2.add(btn_themgiohang, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, -1, -1));

        btn_capnhatgio.setBackground(new java.awt.Color(186, 79, 84));
        btn_capnhatgio.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_capnhatgio.setForeground(new java.awt.Color(255, 255, 255));
        btn_capnhatgio.setText("Xóa giỏ");
        btn_capnhatgio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_capnhatgioActionPerformed(evt);
            }
        });
        jPanel2.add(btn_capnhatgio, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, -1, -1));

        buttonGroup1.add(rdo_tatca);
        rdo_tatca.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rdo_tatca.setText("Tất cả");
        rdo_tatca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rdo_tatcaMouseClicked(evt);
            }
        });
        jPanel2.add(rdo_tatca, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, -1, -1));

        buttonGroup1.add(rdo_dathanhtoan);
        rdo_dathanhtoan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rdo_dathanhtoan.setText("Đã thanh toán");
        rdo_dathanhtoan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rdo_dathanhtoanMouseClicked(evt);
            }
        });
        jPanel2.add(rdo_dathanhtoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 390, -1, -1));

        buttonGroup1.add(rdo_chuathanhtoan);
        rdo_chuathanhtoan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rdo_chuathanhtoan.setText("Chưa thanh toán");
        rdo_chuathanhtoan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rdo_chuathanhtoanMouseClicked(evt);
            }
        });
        jPanel2.add(rdo_chuathanhtoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 390, -1, -1));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Ngày tạo");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 0, 0));
        jLabel8.setText("Tổng tiền:");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 0, 0));
        jLabel9.setText("Giảm giá:");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 0, 0));
        jLabel10.setText("Tổng tiền phải trả:");

        txt_tongtien.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txt_tongtien.setOpaque(true);

        txt_giamgia.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txt_giamgia.setOpaque(true);

        txt_ngaytao.setEditable(false);

        btn_thanhtoan.setBackground(new java.awt.Color(186, 79, 84));
        btn_thanhtoan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_thanhtoan.setForeground(new java.awt.Color(255, 255, 255));
        btn_thanhtoan.setText("Thanh Toán");
        btn_thanhtoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_thanhtoanActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Mã nhân viên");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setText("Khách Hàng");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel16.setText("Khuyến Mãi");

        cbo_khuyenmai.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbo_khuyenmaiItemStateChanged(evt);
            }
        });

        btn_lammoi.setBackground(new java.awt.Color(186, 79, 84));
        btn_lammoi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_lammoi.setForeground(new java.awt.Color(255, 255, 255));
        btn_lammoi.setText("Làm Mới");
        btn_lammoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_lammoiActionPerformed(evt);
            }
        });

        txt_tienphaitra.setEditable(false);
        txt_tienphaitra.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txt_tienphaitra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_tienphaitraMouseClicked(evt);
            }
        });

        txt_tennhanvien.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(59, 59, 59)
                .addComponent(txt_tennhanvien, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addGap(67, 67, 67)
                .addComponent(cbo_khachhang, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel16)
                .addGap(68, 68, 68)
                .addComponent(cbo_khuyenmai, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel5)
                .addGap(83, 83, 83)
                .addComponent(txt_ngaytao, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel8)
                .addGap(77, 77, 77)
                .addComponent(txt_tongtien, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel9)
                .addGap(81, 81, 81)
                .addComponent(txt_giamgia, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel10)
                .addGap(31, 31, 31)
                .addComponent(txt_tienphaitra, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(btn_thanhtoan)
                .addGap(49, 49, 49)
                .addComponent(btn_lammoi))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_tennhanvien, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(32, 32, 32)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbo_khachhang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(34, 34, 34)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel16))
                    .addComponent(cbo_khuyenmai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel5))
                    .addComponent(txt_ngaytao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel8))
                    .addComponent(txt_tongtien, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel9))
                    .addComponent(txt_giamgia, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel10))
                    .addComponent(txt_tienphaitra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_thanhtoan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_lammoi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_hoadonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hoadonActionPerformed
//        HoaDon hoaDon = new HoaDon();
//        KhachHang kh = (KhachHang) cbo_khachhang.getSelectedItem();
//        hoaDon.setNgayTao(new Date());
//        hoaDon.setTrangThai(0);
//        hoaDon.setIdNV(nhanVienService.getIdNvByName(txt_tennhanvien.getText()));
//        hoaDon.setIdKH(kh.getId());
//
//        hoaDonService.insert(hoaDon);
//        JOptionPane.showMessageDialog(this, "Tạo hóa đơn thành công");
//        fillHoaDon(hoaDonService.getListHoaDon());
    }//GEN-LAST:event_btn_hoadonActionPerformed

    private void tbl_hoadonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_hoadonMouseClicked
//        int index = tbl_hoadon.getSelectedRow();
//        try {
//            txt_ngaytao.setText(tbl_hoadon.getValueAt(index, 2).toString());
//        } catch (Exception e) {
////            return;
//        } finally {
//            txt_ngaytao.setText(tbl_hoadon.getValueAt(index, 2).toString());
//        }
    }//GEN-LAST:event_tbl_hoadonMouseClicked

    private void btn_lammoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lammoiActionPerformed
//        clearForm();
    }//GEN-LAST:event_btn_lammoiActionPerformed

    private void txt_tienphaitraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_tienphaitraMouseClicked

    }//GEN-LAST:event_txt_tienphaitraMouseClicked

    private void btn_themgiohangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themgiohangActionPerformed
//        List<SanPham> listSP = sanPhamService.getListSP();
//        int index = tbl_sanpham.getSelectedRow();
//        GioHang gioHang = new GioHang();
//
//        if (index < 0) {
//            JOptionPane.showMessageDialog(this, "Vui lòng chọn sản phẩm!");
//            return;
//        }
//        try {
//            String sl = JOptionPane.showInputDialog(this, "Mời bạn nhập số lượng", "Nhập", HIDE_ON_CLOSE);
//            if (listSP.get(index).getSLTon() < Integer.parseInt(sl)) {
//                JOptionPane.showMessageDialog(this, "Số lượng sản phẩm không đủ để đáp ứng nhu cầu của quý khách!\n(Số lượng tồn: " + listSP.get(index).getSLTon() + ")");
//                return;
//            }
//
//            if (Integer.parseInt(sl) < 0) {
//                JOptionPane.showMessageDialog(this, "Số lượng không được âm!");
//                return;
//            }
//
//            if (Integer.parseInt(sl) == 0) {
//                JOptionPane.showMessageDialog(this, "Số lượng phải lớn hơn 0");
//                return;
//            }
//
//            if (timMaGioHang(tbl_sanpham.getValueAt(index, 2).toString().trim()) == 1) {
//                for (int i = 0; i < tbl_giohang.getRowCount(); i++) {
//                    if (tbl_sanpham.getValueAt(index, 2).toString().trim().equalsIgnoreCase(tbl_giohang.getValueAt(i, 2).toString().trim())) {
//                        int slSP = Integer.parseInt(tbl_sanpham.getValueAt(index, 5).toString());
//                        int so1 = Integer.parseInt(tbl_giohang.getValueAt(i, 4).toString().trim()) + Integer.parseInt(sl);
//                        if (slSP < so1) {
//                            JOptionPane.showMessageDialog(this, "Số lượng sản phẩm không đủ để đáp ứng nhu cầu của quý khách!\n(Số lượng tồn: " + listSP.get(index).getSLTon() + ")");
//                            return;
//                        }
//                    }
//                }
//
//                for (int i = 0; i < tbl_giohang.getRowCount(); i++) {
//                    if (tbl_sanpham.getValueAt(index, 2).toString().trim().equalsIgnoreCase(tbl_giohang.getValueAt(i, 2).toString().trim())) {
//                        int so = Integer.parseInt(tbl_giohang.getValueAt(i, 4).toString().trim()) + Integer.parseInt(sl);
//                        gioHang.setId((int) tbl_sanpham.getValueAt(index, 1));
//                        gioHang.setMa(tbl_sanpham.getValueAt(index, 2).toString());
//                        gioHang.setTen(tbl_sanpham.getValueAt(index, 3).toString());
//                        gioHang.setSoLuong(so);
//                        gioHang.setDonGia((Double) tbl_sanpham.getValueAt(index, 4));
//                        listGioHang.set(i, gioHang);
//                        fillGioHang(listGioHang);
//                    }
//                }

//            } else {
//                gioHang.setId((int) tbl_sanpham.getValueAt(index, 1));
//                gioHang.setMa(tbl_sanpham.getValueAt(index, 2).toString());
//                gioHang.setTen(tbl_sanpham.getValueAt(index, 3).toString());
//                gioHang.setSoLuong(Integer.parseInt(sl));
//                gioHang.setDonGia((Double) tbl_sanpham.getValueAt(index, 4));
//                listGioHang.add(gioHang);
//                fillGioHang(listGioHang);
//            }
//        } catch (HeadlessException | NumberFormatException e) {
//            JOptionPane.showMessageDialog(this, "Bạn chưa nhập số lượng");
//        }
//
//        double tongTien = 0;
//        for (int i = 0; i < listGioHang.size(); i++) {
//            GioHang gh = listGioHang.get(i);
//            tongTien += gh.getDonGia() * gh.getSoLuong();
//        }
//        txt_tongtien.setText(String.valueOf(tongTien));
    }//GEN-LAST:event_btn_themgiohangActionPerformed

    private void btn_capnhatgioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_capnhatgioActionPerformed
        int indexGH = tbl_giohang.getSelectedRow();
        if (indexGH >= 0) {
//            int slSP = banHangService.getSLById((int) tbl_giohang.getValueAt(indexGH, 1));
//            String slGH = tbl_giohang.getValueAt(indexGH, 4).toString();
//            int soLuong = slSP + Integer.parseInt(slGH);
//            String ma = tbl_giohang.getValueAt(indexGH, 2).toString();
//            sanPhamService.update(ma, soLuong);
//            fillSanPham(sanPhamService.getListSP());

//            listGioHang.remove(indexGH);
//            fillGioHang(listGioHang);
        } else {
//            for (int i = 0; i < listGioHang.size(); i++) {
//                GioHang get = listGioHang.get(i);
//                String ma = tbl_giohang.getValueAt(i, 2).toString();
//                String slGH = tbl_giohang.getValueAt(i, 4).toString();
//                int sl = Integer.parseInt(slGH) + banHangService.getSLById(Integer.parseInt(tbl_giohang.getValueAt(i, 1).toString()));
//                sanPhamService.update(ma, sl);
//            }
//            fillSanPham(sanPhamService.getListSP());

//            listGioHang.clear();
//            fillGioHang(listGioHang);
        }

    }//GEN-LAST:event_btn_capnhatgioActionPerformed

    private void btn_thanhtoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_thanhtoanActionPerformed
//        if (checkValidate()) {
//            double RanDomDouble = Math.random();
//            RanDomDouble = RanDomDouble * 500 + 1;
//            int ranInt = (int) RanDomDouble;
//            int indexHD = tbl_hoadon.getSelectedRow();
//
//            HoaDon hoaDon = new HoaDon();
//            hoaDon.setIdNV(nhanVienService.getIdNvByName(txt_tennhanvien.getText()));
//            KhachHang kh = (KhachHang) cbo_khachhang.getSelectedItem();
//            hoaDon.setIdKH(kh.getId());
//            hoaDon.setMa("HD" + ranInt);
//            hoaDon.setNgayThanhToan(new Date());
//            hoaDon.setTongtien(Double.valueOf(txt_tongtien.getText()));
//            hoaDon.setTrangThai(1);
//            hoaDon.setId((int) tbl_hoadon.getValueAt(indexHD, 0));
//            hoaDonService.update(hoaDon);
//            fillHoaDon(hoaDonService.getListHoaDon());
//
//            ChiTietHoaDon cthd = new ChiTietHoaDon();
//            KhuyenMai km = (KhuyenMai) cbo_khuyenmai.getSelectedItem();
//            for (int i = 0; i < listGioHang.size(); i++) {
//                GioHang get = listGioHang.get(i);
//                cthd.setIdSP(get.getId());
//                cthd.setIdHoaDon((int) tbl_hoadon.getValueAt(indexHD, 0));
//                cthd.setIdKM(km.getId());
//                cthd.setSoLuong(get.getSoLuong());
//                cthd.setDonGia(get.getSoLuong() * get.getDonGia());
//                banHangService.insert(cthd);
//            }
//            JOptionPane.showMessageDialog(this, "Thanh toán thành công");
//
//            int inHoaDon = JOptionPane.showConfirmDialog(this, "Bạn có muốn in hóa đơn không", "In hóa đơn", JOptionPane.YES_NO_OPTION);
//            if (inHoaDon == JOptionPane.YES_OPTION) {
//
//                String path = "";
//                JFileChooser chooser = new JFileChooser("D:\\");
//                chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
//                int x = chooser.showSaveDialog(this);
//
//                if (x == JFileChooser.APPROVE_OPTION) {
//                    path = chooser.getSelectedFile().getPath();
//                }
//
//                Document doc = new Document();
//
//                try {
//                    PdfWriter.getInstance(doc, new FileOutputStream(path + "hoadonchitiet.pdf"));
//                    doc.open();
//
//                    String ma = "HD" + ranInt;
//                    String tenKH = kh.getTen();
//                    String ngayTao = txt_ngaytao.getText();
//                    String tongTien = txt_tienphaitra.getText();
//                    String khuyenMai = String.valueOf(km.getGiaTri());
//                    PdfPTable tbl3 = new PdfPTable(3);
//
//                    for (int i = 0; i < tbl_giohang.getRowCount(); i++) {
//                        String tenSP = tbl_giohang.getValueAt(i, 3).toString();
//                        String soLuong = tbl_giohang.getValueAt(i, 4).toString();
//                        String donGia = tbl_giohang.getValueAt(i, 6).toString();
//                        PdfPCell cellTenSP = new PdfPCell(new Phrase(tenSP));
//                        PdfPCell cellDonGia = new PdfPCell(new Phrase(donGia));
//                        PdfPCell cellSoLuong = new PdfPCell(new Phrase("SL: " + soLuong));
//                        cellTenSP.setBorderColor(Color.WHITE);
//                        cellDonGia.setBorderColor(Color.WHITE);
//                        cellSoLuong.setBorderColor(Color.WHITE);
//                        cellTenSP.setPaddingLeft(30);
//                        cellTenSP.setPaddingBottom(10);
//                        cellDonGia.setPaddingLeft(72);
//                        cellDonGia.setPaddingBottom(10);
//                        cellSoLuong.setPaddingLeft(10);
//                        cellSoLuong.setPaddingBottom(10);
//                        tbl3.addCell(cellTenSP);
//                        tbl3.addCell(cellDonGia);
//                        tbl3.addCell(cellSoLuong);
//                    }
//
//                    PdfPTable tblTenCuaHang = new PdfPTable(1);
//                    PdfPTable tblLoiCamOn = new PdfPTable(1);
//                    PdfPCell cellTitle = new PdfPCell(new Phrase("SEVENT STORE"));
//                    PdfPCell cellEnd = new PdfPCell(new Phrase("CAM ON QUY KHACH"));
//                    PdfPCell cellLater = new PdfPCell(new Phrase("HEN GAP LAI!"));
//                    cellTitle.setBorderColor(Color.WHITE);
//                    cellEnd.setBorderColor(Color.WHITE);
//                    cellLater.setBorderColor(Color.WHITE);
//                    cellTitle.setPaddingBottom(50);
//                    cellTitle.setPaddingLeft(130);
//                    tblTenCuaHang.addCell(cellTitle);
//                    cellEnd.setPaddingTop(50);
//                    cellEnd.setPaddingLeft(100);
//                    cellLater.setPaddingTop(10);
//                    cellLater.setPaddingLeft(120);
//
//                    PdfPTable tblDanhSach = new PdfPTable(2);
//                    PdfPTable tblTongTien = new PdfPTable(2);
//                    LocalDate localDate = LocalDate.now();
//                    PdfPCell cellMa = new PdfPCell(new Phrase("Ma Hoa Don"));
//                    PdfPCell cellMa1 = new PdfPCell(new Phrase(ma));
//                    PdfPCell cellKH = new PdfPCell(new Phrase("Khach Hang"));
//                    PdfPCell cellKH1 = new PdfPCell(new Phrase(tenKH));
//                    PdfPCell cellNgayTao = new PdfPCell(new Phrase("Ngay Tao"));
//                    PdfPCell cellNgayTao1 = new PdfPCell(new Phrase(ngayTao));
//                    PdfPCell cellNgayThanhToan = new PdfPCell(new Phrase("Ngay Thanh Toan"));
//                    PdfPCell cellNgayThanhToan1 = new PdfPCell(new Phrase(localDate.toString()));
//                    PdfPCell cellVachKe = new PdfPCell(new Phrase("--------------------------------------------"));
//                    PdfPCell cellVachKe1 = new PdfPCell(new Phrase("--------------------------------------------"));
//                    PdfPCell cellKhuyenMai = new PdfPCell(new Phrase("Khuyen Mai"));
//                    PdfPCell cellKhuyenMai1 = new PdfPCell(new Phrase(khuyenMai + "%"));
//                    PdfPCell cellTongTien = new PdfPCell(new Phrase("Tong Tien"));
//                    PdfPCell cellTongTien1 = new PdfPCell(new Phrase(tongTien));
//
//                    cellMa.setBorderColor(Color.WHITE);
//                    cellMa1.setBorderColor(Color.WHITE);
//                    cellMa.setPaddingBottom(10);
//                    cellMa.setPaddingLeft(30);
//                    cellKH.setBorderColor(Color.WHITE);
//                    cellKH1.setBorderColor(Color.WHITE);
//                    cellKH.setPaddingBottom(10);
//                    cellKH.setPaddingLeft(30);
//                    cellNgayTao.setBorderColor(Color.WHITE);
//                    cellNgayTao1.setBorderColor(Color.WHITE);
//                    cellNgayTao.setPaddingBottom(10);
//                    cellNgayTao.setPaddingLeft(30);
//                    cellNgayThanhToan.setBorderColor(Color.WHITE);
//                    cellNgayThanhToan1.setBorderColor(Color.WHITE);
//                    cellNgayThanhToan.setPaddingBottom(10);
//                    cellNgayThanhToan.setPaddingLeft(30);
//                    cellVachKe.setBorderColor(Color.WHITE);
//                    cellVachKe1.setBorderColor(Color.WHITE);
//                    cellVachKe.setPaddingBottom(10);
//                    cellVachKe.setPaddingLeft(30);
//                    cellKhuyenMai.setBorderColor(Color.WHITE);
//                    cellKhuyenMai1.setBorderColor(Color.WHITE);
//                    cellKhuyenMai.setPaddingBottom(10);
//                    cellKhuyenMai.setPaddingLeft(30);
//                    cellTongTien.setBorderColor(Color.WHITE);
//                    cellTongTien1.setBorderColor(Color.WHITE);
//                    cellTongTien.setPaddingBottom(10);
//                    cellTongTien.setPaddingLeft(30);
//
//                    tblDanhSach.addCell(cellMa);
//                    tblDanhSach.addCell(cellMa1);
//                    tblDanhSach.addCell(cellKH);
//                    tblDanhSach.addCell(cellKH1);
//                    tblDanhSach.addCell(cellNgayTao);
//                    tblDanhSach.addCell(cellNgayTao1);
//                    tblDanhSach.addCell(cellNgayThanhToan);
//                    tblDanhSach.addCell(cellNgayThanhToan1);
//                    tblDanhSach.addCell(cellVachKe);
//                    tblDanhSach.addCell(cellVachKe1);
//
//                    tblTongTien.addCell(cellKhuyenMai);
//                    tblTongTien.addCell(cellKhuyenMai1);
//                    tblTongTien.addCell(cellTongTien);
//                    tblTongTien.addCell(cellTongTien1);
//                    tblLoiCamOn.addCell(cellEnd);
//                    tblLoiCamOn.addCell(cellLater);
//
//                    doc.add(tblTenCuaHang);
//                    doc.add(tblDanhSach);
//                    doc.add(tbl3);
//                    doc.add(tblTongTien);
//                    doc.add(tblLoiCamOn);
//
//                } catch (FileNotFoundException | DocumentException ex) {
//                    ex.getMessage();
//                }
//                doc.close();
//            }
//
//            for (int i = 0; i < listGioHang.size(); i++) {
//                String ma = tbl_giohang.getValueAt(i, 2).toString();
//                String slGH = tbl_giohang.getValueAt(i, 4).toString();
//                int sl = banHangService.getSLById(Integer.parseInt(tbl_giohang.getValueAt(i, 1).toString())) - Integer.parseInt(slGH);
//                sanPhamService.update(ma, sl);
//            }
//            fillSanPham(sanPhamService.getListSP());
//
//            listGioHang.clear();
//            fillGioHang(listGioHang);
//            clearForm();
//        }
    }//GEN-LAST:event_btn_thanhtoanActionPerformed

    private void cbo_khuyenmaiItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbo_khuyenmaiItemStateChanged
//        KhuyenMai km = (KhuyenMai) cbo_khuyenmai.getSelectedItem();
//        txt_giamgia.setText(String.valueOf(km.getGiaTri()));
//        double tongTien, giamGia, tienGiamDuoc, tienPhaiTra;
//        tongTien = Double.parseDouble(txt_tongtien.getText());
//        giamGia = Double.parseDouble(txt_giamgia.getText());
//        tienGiamDuoc = (tongTien * giamGia) / 100;
//        tienPhaiTra = tongTien - tienGiamDuoc;
//        txt_tienphaitra.setText(String.valueOf(tienPhaiTra));
    }//GEN-LAST:event_cbo_khuyenmaiItemStateChanged

    private void rdo_tatcaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rdo_tatcaMouseClicked
//        fillHoaDon(hoaDonService.getListHoaDon());
    }//GEN-LAST:event_rdo_tatcaMouseClicked

    private void rdo_dathanhtoanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rdo_dathanhtoanMouseClicked
//        fillHoaDon(hoaDonService.filterHoaDonByTT(1));
    }//GEN-LAST:event_rdo_dathanhtoanMouseClicked

    private void rdo_chuathanhtoanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rdo_chuathanhtoanMouseClicked
//        fillHoaDon(hoaDonService.filterHoaDonByTT(0));
    }//GEN-LAST:event_rdo_chuathanhtoanMouseClicked

    private void txt_timkiemKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_timkiemKeyPressed
//        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
//            if (txt_timkiem.getText().isEmpty()) {
//                fillSanPham(sanPhamService.getListSP());
//            }
//            fillSanPham(sanPhamService.timKiemK(txt_timkiem.getText()));
//        }
    }//GEN-LAST:event_txt_timkiemKeyPressed

//    private void fillHoaDon(List<HoaDon> list) {
//        defaultTableModelHoaDon = (DefaultTableModel) tbl_hoadon.getModel();
//        defaultTableModelHoaDon.setRowCount(0);
//        for (HoaDon h : list) {
//                String tt = h.getTrangThai() == 0 ? "Chưa thanh toán" : "Đã thanh toán";
//                defaultTableModelHoaDon.addRow(new Object[]{h.getId(), h.getMa(), h.getNgayTao(), h.getNgayThanhToan(), tt});
//        }
//    }
//
//    private void fillGioHang(List<GioHang> list) {
//        defaultTableModelGioHang = (DefaultTableModel) tbl_giohang.getModel();
//        defaultTableModelGioHang.setRowCount(0);
//        int i = 1;
//        for (GioHang g : list) {
//
//            defaultTableModelGioHang.addRow(new Object[]{i++, g.getId(), g.getMa(), g.getTen(), g.getSoLuong(), g.getDonGia(), g.getSoLuong() * g.getDonGia()});
//        }
//    }
//
//    private void fillSanPham(List<SanPham> list) {
//        defaultTableModelSanPham = (DefaultTableModel) tbl_sanpham.getModel();
//        defaultTableModelSanPham.setRowCount(0);
//        int g = 1;
//        for (SanPham s : list) {
//
//            defaultTableModelSanPham.addRow(new Object[]{g++, s.getId(), s.getMa(), s.getTen(), s.getGiaBan(), s.getSLTon()});
//        }
//    }
//
//    private void clearForm() {
//        txt_ngaytao.setText("");
//        txt_tongtien.setText("");
//        txt_giamgia.setText("");
//        txt_tienphaitra.setText("");
//    }
//
//    private boolean checkValidate() {
//        if (txt_tennhanvien.getText().isEmpty()) {
//            JOptionPane.showMessageDialog(this, "Tên nhân viên không được trống");
//            txt_tennhanvien.requestFocus();
//            return false;
//        }
//
//        if (txt_ngaytao.getText().isEmpty()) {
//            JOptionPane.showMessageDialog(this, "Tên nhân viên không được trống");
//            txt_ngaytao.requestFocus();
//            return false;
//        }
//
//        if (txt_tongtien.getText().isEmpty()) {
//            JOptionPane.showMessageDialog(this, "Tổng tiền không được trống");
//            txt_tongtien.requestFocus();
//            return false;
//        }
//
//        if (txt_giamgia.getText().isEmpty()) {
//            JOptionPane.showMessageDialog(this, "Giảm giá không được trống");
//            txt_giamgia.requestFocus();
//            return false;
//        }
//
//        if (txt_tienphaitra.getText().isEmpty()) {
//            JOptionPane.showMessageDialog(this, "Tiền phải trả không được trống");
//            txt_tienphaitra.requestFocus();
//            return false;
//        }
//
//        return true;
//    }
//
//    private int timSLGioHang(String ma, int sl) {
//        for (int i = 0; i < listGioHang.size(); i++) {
//            GioHang gh = listGioHang.get(i);
//            if (gh.getMa().trim().equalsIgnoreCase(ma)) {
//                return sl + gh.getSoLuong();
//            }
//        }
//        return sl;
//    }
//
//    private int timMaGioHang(String ma) {
//        for (int i = 0; i < listGioHang.size(); i++) {
//            GioHang gh = listGioHang.get(i);
//            if (gh.getMa().trim().equalsIgnoreCase(ma)) {
//                return 1;
//            }
//        }
//        return 2;
//    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_capnhatgio;
    private javax.swing.JButton btn_hoadon;
    private javax.swing.JButton btn_lammoi;
    private javax.swing.JButton btn_thanhtoan;
    private javax.swing.JButton btn_themgiohang;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbo_khachhang;
    private javax.swing.JComboBox<KhuyenMai> cbo_khuyenmai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JRadioButton rdo_chuathanhtoan;
    private javax.swing.JRadioButton rdo_dathanhtoan;
    private javax.swing.JRadioButton rdo_tatca;
    private javax.swing.JTable tbl_giohang;
    private javax.swing.JTable tbl_hoadon;
    private javax.swing.JTable tbl_sanpham;
    private javax.swing.JLabel txt_giamgia;
    private javax.swing.JTextField txt_ngaytao;
    private javax.swing.JLabel txt_tennhanvien;
    private javax.swing.JTextField txt_tienphaitra;
    private javax.swing.JTextField txt_timkiem;
    private javax.swing.JLabel txt_tongtien;
    // End of variables declaration//GEN-END:variables
}
