package View;

import Model.ChiTietSanPham;
import Model.Cpu;
import Model.Hang;
import Model.ManHinh;
import Model.MauSac;
import Model.OCung;
import Model.Ram;
import Model.SanPham;
import Model.Vga;
import Service.CPUService;
import Service.ChiTietSanPhamService;
import Service.HangService;
import Service.ManHinhService;
import Service.MauSacService;
import Service.OCungService;
import Service.RamService;
import Service.SanPhamService;
import Service.VGAService;
import ViewModel.ChiTietSanPhamModel;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author quyen
 */
public class JPanelSanPham extends javax.swing.JPanel {

    HangService hS = new HangService();
    OCungService ocS = new OCungService();
    RamService rS = new RamService();
    ManHinhService mhS = new ManHinhService();
    VGAService vS = new VGAService();
    CPUService cS = new CPUService();
    MauSacService msS = new MauSacService();
    SanPhamService spS = new SanPhamService();
    ChiTietSanPhamService ctspService = new ChiTietSanPhamService();
//    List<SanPham> listSP = new ArrayList<>();

    public JPanelSanPham() {
        initComponents();
        List<Hang> listH = hS.getListHang();
        cboHang.setModel(new DefaultComboBoxModel(listH.toArray()));
        List<Cpu> listC = cS.getListCPU();
        cboCPU.setModel(new DefaultComboBoxModel(listC.toArray()));
        List<Ram> listR = rS.getAllRam();
        cboRam.setModel(new DefaultComboBoxModel(listR.toArray()));
        List<OCung> listO = ocS.getAllOCung();
        cboOcung.setModel(new DefaultComboBoxModel(listO.toArray()));
        List<Vga> listV = vS.getListDB();
        cboVGA.setModel(new DefaultComboBoxModel(listV.toArray()));
        List<ManHinh> listMH = mhS.getListManHinh();
        cboManHinh.setModel(new DefaultComboBoxModel(listMH.toArray()));
        List<MauSac> listMS = msS.getAllMauSac();
        cboMauSac.setModel(new DefaultComboBoxModel(listMS.toArray()));
        List<SanPham> listSP = spS.getAllSanPham();
        cbo_sanpham.setModel(new DefaultComboBoxModel(listSP.toArray()));

        fillTB(ctspService.getListSanPham());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSanPham = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cbo_sanpham = new javax.swing.JComboBox<>();
        cboCPU = new javax.swing.JComboBox<>();
        cboRam = new javax.swing.JComboBox<>();
        cboOcung = new javax.swing.JComboBox<>();
        cboHang = new javax.swing.JComboBox<>();
        cboVGA = new javax.swing.JComboBox<>();
        cboManHinh = new javax.swing.JComboBox<>();
        cboMauSac = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        btn_vga = new javax.swing.JButton();
        btn_cpu = new javax.swing.JButton();
        btn_hang = new javax.swing.JButton();
        btn_ram = new javax.swing.JButton();
        btn_ocung = new javax.swing.JButton();
        btn_sanpham = new javax.swing.JButton();
        btn_mausac = new javax.swing.JButton();
        btn_manhinh = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txt_gianhap = new javax.swing.JTextField();
        txt_giaban = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtSLTon = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        btn_sua = new javax.swing.JButton();
        btn_moi = new javax.swing.JButton();
        btn_them = new javax.swing.JButton();
        btn_xoa = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        rdo_con = new javax.swing.JRadioButton();
        rdo_khong = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(186, 79, 84));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("          Sản Phẩm");
        jLabel2.setOpaque(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1070, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 60));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblSanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Sản Phẩm", "Cpu", "Hãng", "Màn Hình", "Màu Sắc", "Ổ cứng", "Ram", "Vga", "Số lượng tồn", "Giá Nhập", "Giá Bán", "Ngày Tạo", "Ngày Nhập", "Trạng Thái"
            }
        ));
        tblSanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSanPhamMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblSanPham);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 300));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1050, 310));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("VGA");
        jLabel4.setMaximumSize(new java.awt.Dimension(100, 50));
        jLabel4.setMinimumSize(new java.awt.Dimension(40, 20));
        jLabel4.setPreferredSize(new java.awt.Dimension(40, 20));
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 32, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("RAM");
        jLabel5.setMinimumSize(new java.awt.Dimension(40, 20));
        jLabel5.setPreferredSize(new java.awt.Dimension(40, 20));
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Ổ cứng");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 0, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("CPU");
        jLabel7.setMaximumSize(new java.awt.Dimension(100, 50));
        jLabel7.setMinimumSize(new java.awt.Dimension(40, 20));
        jLabel7.setPreferredSize(new java.awt.Dimension(40, 20));
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 32, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Sản phẩm");
        jLabel8.setMaximumSize(new java.awt.Dimension(100, 50));
        jLabel8.setMinimumSize(new java.awt.Dimension(40, 20));
        jLabel8.setPreferredSize(new java.awt.Dimension(40, 20));
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 100, 60, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Màn hình");
        jLabel9.setMaximumSize(new java.awt.Dimension(100, 50));
        jLabel9.setMinimumSize(new java.awt.Dimension(40, 20));
        jLabel9.setPreferredSize(new java.awt.Dimension(40, 20));
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 60, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Màu sắc");
        jLabel10.setMaximumSize(new java.awt.Dimension(100, 50));
        jLabel10.setMinimumSize(new java.awt.Dimension(40, 20));
        jLabel10.setPreferredSize(new java.awt.Dimension(40, 20));
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, 60, -1));

        jPanel4.add(cbo_sanpham, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 120, 130, -1));

        jPanel4.add(cboCPU, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 130, -1));

        jPanel4.add(cboRam, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, 130, -1));

        jPanel4.add(cboOcung, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 30, 130, -1));

        jPanel4.add(cboHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 130, -1));

        jPanel4.add(cboVGA, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 130, -1));

        jPanel4.add(cboManHinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 130, -1));

        jPanel4.add(cboMauSac, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 120, 130, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Hãng");
        jLabel3.setMaximumSize(new java.awt.Dimension(100, 50));
        jLabel3.setMinimumSize(new java.awt.Dimension(40, 20));
        jLabel3.setPreferredSize(new java.awt.Dimension(40, 20));
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 32, -1));

        btn_vga.setBackground(new java.awt.Color(186, 79, 84));
        btn_vga.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_vga.setForeground(new java.awt.Color(255, 255, 255));
        btn_vga.setText("VGA");
        btn_vga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_vgaActionPerformed(evt);
            }
        });
        jPanel4.add(btn_vga, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 130, 28));

        btn_cpu.setBackground(new java.awt.Color(186, 79, 84));
        btn_cpu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_cpu.setForeground(new java.awt.Color(255, 255, 255));
        btn_cpu.setText("CPU");
        btn_cpu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cpuActionPerformed(evt);
            }
        });
        jPanel4.add(btn_cpu, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 130, 28));

        btn_hang.setBackground(new java.awt.Color(186, 79, 84));
        btn_hang.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_hang.setForeground(new java.awt.Color(255, 255, 255));
        btn_hang.setText("Hãng");
        btn_hang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hangActionPerformed(evt);
            }
        });
        jPanel4.add(btn_hang, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 130, 28));

        btn_ram.setBackground(new java.awt.Color(186, 79, 84));
        btn_ram.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_ram.setForeground(new java.awt.Color(255, 255, 255));
        btn_ram.setText("RAM");
        btn_ram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ramActionPerformed(evt);
            }
        });
        jPanel4.add(btn_ram, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 60, 130, 28));

        btn_ocung.setBackground(new java.awt.Color(186, 79, 84));
        btn_ocung.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_ocung.setForeground(new java.awt.Color(255, 255, 255));
        btn_ocung.setText("Ổ cứng");
        btn_ocung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ocungActionPerformed(evt);
            }
        });
        jPanel4.add(btn_ocung, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 60, 130, 28));

        btn_sanpham.setBackground(new java.awt.Color(186, 79, 84));
        btn_sanpham.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_sanpham.setForeground(new java.awt.Color(255, 255, 255));
        btn_sanpham.setText("Sản Phẩm");
        btn_sanpham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sanphamActionPerformed(evt);
            }
        });
        jPanel4.add(btn_sanpham, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 150, 130, 28));

        btn_mausac.setBackground(new java.awt.Color(186, 79, 84));
        btn_mausac.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_mausac.setForeground(new java.awt.Color(255, 255, 255));
        btn_mausac.setText("Màu Sắc");
        btn_mausac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mausacActionPerformed(evt);
            }
        });
        jPanel4.add(btn_mausac, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 150, 130, 28));

        btn_manhinh.setBackground(new java.awt.Color(186, 79, 84));
        btn_manhinh.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_manhinh.setForeground(new java.awt.Color(255, 255, 255));
        btn_manhinh.setText("Màn Hình");
        btn_manhinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_manhinhActionPerformed(evt);
            }
        });
        jPanel4.add(btn_manhinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 130, 28));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 670, 190));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setForeground(new java.awt.Color(186, 79, 84));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setText("Giá bán");
        jPanel5.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 50, 20));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setText("Trạng Thái");
        jPanel5.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 70, 20));

        txt_gianhap.setBorder(null);
        jPanel5.add(txt_gianhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 130, 20));

        txt_giaban.setBorder(null);
        jPanel5.add(txt_giaban, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 130, 20));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setText("Giá nhập");
        jPanel5.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 80, 20));

        jSeparator1.setForeground(new java.awt.Color(186, 79, 84));
        jPanel5.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 130, 10));

        txtSLTon.setBorder(null);
        jPanel5.add(txtSLTon, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 130, 20));

        jSeparator4.setForeground(new java.awt.Color(186, 79, 84));
        jPanel5.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 130, 10));

        jSeparator5.setForeground(new java.awt.Color(186, 79, 84));
        jPanel5.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 130, 10));

        btn_sua.setBackground(new java.awt.Color(186, 79, 84));
        btn_sua.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_sua.setForeground(new java.awt.Color(255, 255, 255));
        btn_sua.setText("Sửa");
        btn_sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_suaActionPerformed(evt);
            }
        });
        jPanel5.add(btn_sua, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 70, 32));

        btn_moi.setBackground(new java.awt.Color(186, 79, 84));
        btn_moi.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_moi.setForeground(new java.awt.Color(255, 255, 255));
        btn_moi.setText("Mới");
        btn_moi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_moiActionPerformed(evt);
            }
        });
        jPanel5.add(btn_moi, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, 70, 32));

        btn_them.setBackground(new java.awt.Color(186, 79, 84));
        btn_them.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_them.setForeground(new java.awt.Color(255, 255, 255));
        btn_them.setText("Thêm");
        btn_them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themActionPerformed(evt);
            }
        });
        jPanel5.add(btn_them, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 70, 32));

        btn_xoa.setBackground(new java.awt.Color(186, 79, 84));
        btn_xoa.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_xoa.setForeground(new java.awt.Color(255, 255, 255));
        btn_xoa.setText("Xóa");
        btn_xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoaActionPerformed(evt);
            }
        });
        jPanel5.add(btn_xoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 70, 32));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setText("Số lượng tồn");
        jPanel5.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 90, 20));

        buttonGroup1.add(rdo_con);
        rdo_con.setText("Còn");
        jPanel5.add(rdo_con, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, -1, -1));

        buttonGroup1.add(rdo_khong);
        rdo_khong.setText("Không");
        jPanel5.add(rdo_khong, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, 60, -1));

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 340, 380, 280));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Tìm kiếm");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, -1));

        jTextField1.setBorder(null);
        jTextField1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel2.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 160, 20));

        jSeparator2.setForeground(new java.awt.Color(186, 79, 84));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 160, 10));

        jButton1.setBackground(new java.awt.Color(186, 79, 84));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Tìm kiếm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 350, -1, -1));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 1070, 620));
    }// </editor-fold>//GEN-END:initComponents

    private void tblSanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSanPhamMouseClicked
        int index = tblSanPham.getSelectedRow();
        txtSLTon.setText(tblSanPham.getValueAt(index, 9).toString());
        txt_gianhap.setText(tblSanPham.getValueAt(index, 10).toString());
        txt_giaban.setText(tblSanPham.getValueAt(index, 11).toString());
        cboCPU.setSelectedItem(tblSanPham.getValueAt(index, 2));
//        mouseClickTB(index);
    }//GEN-LAST:event_tblSanPhamMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_hangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hangActionPerformed
        CRUDhang hang = new CRUDhang();
        hang.setVisible(true);
    }//GEN-LAST:event_btn_hangActionPerformed

    private void btn_cpuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cpuActionPerformed
        CRUDcpu cpu = new CRUDcpu();
        cpu.setVisible(true);
    }//GEN-LAST:event_btn_cpuActionPerformed

    private void btn_ramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ramActionPerformed
        CRUDram ram = new CRUDram();
        ram.setVisible(true);
    }//GEN-LAST:event_btn_ramActionPerformed

    private void btn_ocungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ocungActionPerformed
        CRUDocung ocung = new CRUDocung();
        ocung.setVisible(true);
    }//GEN-LAST:event_btn_ocungActionPerformed

    private void btn_vgaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_vgaActionPerformed
        CRUDvga vga = new CRUDvga();
        vga.setVisible(true);
    }//GEN-LAST:event_btn_vgaActionPerformed

    private void btn_manhinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_manhinhActionPerformed
        CRUDmanhinh manhinh = new CRUDmanhinh();
        manhinh.setVisible(true);
    }//GEN-LAST:event_btn_manhinhActionPerformed

    private void btn_mausacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mausacActionPerformed
        CRUDmausac mausac = new CRUDmausac();
        mausac.setVisible(true);
    }//GEN-LAST:event_btn_mausacActionPerformed

    private void btn_sanphamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sanphamActionPerformed
        CRUDsanpham sanpham = new CRUDsanpham();
        sanpham.setVisible(true);
    }//GEN-LAST:event_btn_sanphamActionPerformed

    private void btn_themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themActionPerformed
        int cf = JOptionPane.showConfirmDialog(this, "Bạn có muốn thêm không?", "Thêm", JOptionPane.YES_NO_OPTION);

        if (cf == JOptionPane.YES_OPTION) {
            JOptionPane.showMessageDialog(this, ctspService.insert(getFieldInsert()));
            fillTB(ctspService.getListSanPham());
        }
    }//GEN-LAST:event_btn_themActionPerformed

    private void btn_suaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_suaActionPerformed
        int cf = JOptionPane.showConfirmDialog(this, "Bạn có muốn sửa không?", "Sửa", JOptionPane.YES_NO_OPTION);

        if (cf == JOptionPane.YES_OPTION) {
            JOptionPane.showMessageDialog(this, ctspService.update(getFieldUpdate()));
            fillTB(ctspService.getListSanPham());
        }
    }//GEN-LAST:event_btn_suaActionPerformed

    private void btn_xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoaActionPerformed
        int cf = JOptionPane.showConfirmDialog(this, "Bạn có muốn xóa không?", "Xóa", JOptionPane.YES_NO_OPTION);
        int index = tblSanPham.getSelectedRow();
        ChiTietSanPham ctsp = new ChiTietSanPham();
        ctsp.setId(Integer.parseInt(tblSanPham.getValueAt(index, 0).toString()));
        if (cf == JOptionPane.YES_OPTION) {
            JOptionPane.showMessageDialog(this, ctspService.delete(ctsp));
            fillTB(ctspService.getListSanPham());
        }
    }//GEN-LAST:event_btn_xoaActionPerformed

    private void btn_moiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_moiActionPerformed
        txtSLTon.setText("");
        txt_gianhap.setText("");
        txt_giaban.setText("");
    }//GEN-LAST:event_btn_moiActionPerformed

    private void fillTB(List<ChiTietSanPhamModel> list) {
        DefaultTableModel mol = (DefaultTableModel) tblSanPham.getModel();
        mol.setRowCount(0);
        for (ChiTietSanPhamModel sp : list) {
            mol.addRow(new Object[]{sp.getId(), sp.getSanPham(), sp.getCpu(), sp.getHang(), sp.getManHinh(), sp.getMauSac(),
                sp.getoCung(), sp.getRam(), sp.getVga(), sp.getSlTon(), sp.getGiaNhap(), sp.getGiaBan(), sp.getNgayTao(), sp.getNgayNhap(), sp.getTrangThai()});
        }
    }

    private ChiTietSanPham getFieldInsert() {
        ChiTietSanPham ctsp = new ChiTietSanPham();
        LocalDate date = LocalDate.now();
        Hang h = (Hang) cboHang.getSelectedItem();
        Cpu cpu = (Cpu) cboCPU.getSelectedItem();
        Ram ram = (Ram) cboRam.getSelectedItem();
        OCung oc = (OCung) cboOcung.getSelectedItem();
        ManHinh mh = (ManHinh) cboManHinh.getSelectedItem();
        Vga vga = (Vga) cboVGA.getSelectedItem();
        MauSac ms = (MauSac) cboMauSac.getSelectedItem();
        SanPham sp = (SanPham) cbo_sanpham.getSelectedItem();

        ctsp.setIdSanPham(sp.getId());
        ctsp.setIdHang(h.getId());
        ctsp.setIdCpu(cpu.getId());
        ctsp.setIdRam(ram.getId());
        ctsp.setIdOCung(oc.getId());
        ctsp.setIdVga(vga.getId());
        ctsp.setIdManHinh(mh.getId());
        ctsp.setIdMauSac(ms.getId());
        ctsp.setGiaNhap(Double.valueOf(txt_gianhap.getText()));
        ctsp.setGiaBan(Double.valueOf(txt_giaban.getText()));
        ctsp.setNgayTao(date.format(DateTimeFormatter.ISO_DATE));
        ctsp.setNgayNhap(date.format(DateTimeFormatter.ISO_DATE));
        ctsp.setSlTon(Integer.parseInt(txtSLTon.getText()));
        if (rdo_con.isSelected()) {
            ctsp.setTrangThai(1);
        } else {
            ctsp.setTrangThai(0);
        }

        return ctsp;
    }

    private ChiTietSanPham getFieldUpdate() {
        int index = tblSanPham.getSelectedRow();
        ChiTietSanPham ctsp = new ChiTietSanPham();
        LocalDate date = LocalDate.now();
        Hang h = (Hang) cboHang.getSelectedItem();
        Cpu cpu = (Cpu) cboCPU.getSelectedItem();
        Ram ram = (Ram) cboRam.getSelectedItem();
        OCung oc = (OCung) cboOcung.getSelectedItem();
        ManHinh mh = (ManHinh) cboManHinh.getSelectedItem();
        Vga vga = (Vga) cboVGA.getSelectedItem();
        MauSac ms = (MauSac) cboMauSac.getSelectedItem();
        SanPham sp = (SanPham) cbo_sanpham.getSelectedItem();

        ctsp.setId(Integer.parseInt(tblSanPham.getValueAt(index, 0).toString()));
        ctsp.setIdSanPham(sp.getId());
        ctsp.setIdHang(h.getId());
        ctsp.setIdCpu(cpu.getId());
        ctsp.setIdRam(ram.getId());
        ctsp.setIdOCung(oc.getId());
        ctsp.setIdVga(vga.getId());
        ctsp.setIdManHinh(mh.getId());
        ctsp.setIdMauSac(ms.getId());
        ctsp.setGiaNhap(Double.valueOf(txt_gianhap.getText()));
        ctsp.setGiaBan(Double.valueOf(txt_giaban.getText()));
        ctsp.setNgayNhap(date.format(DateTimeFormatter.ISO_DATE));
        ctsp.setSlTon(Integer.parseInt(txtSLTon.getText()));
        if (rdo_con.isSelected()) {
            ctsp.setTrangThai(1);
        } else {
            ctsp.setTrangThai(0);
        }

        return ctsp;
    }
//
//    public void mouseClickTB(int index) {
//        listSPV = spS.getListSPV();
//        SanPhamViewMD sp = listSPV.get(index);
//        txtMa.setText(sp.getMa());
//        txt_ten.setText(sp.getTen());
//        txt_gianhap.setText(sp.getGiaNhap() + "");
//        txt_giaban.setText(sp.getGiaBan() + "");
//        txtSLTon.setText(sp.getSLTon() + "");
//
//    }
//
//    public void addSP() {
//        Hang h = (Hang) cboHang.getSelectedItem();
//        CPU cpu = (CPU) cboCPU.getSelectedItem();
//        RAM ram = (RAM) cboRam.getSelectedItem();
//        OCung oc = (OCung) cboOcung.getSelectedItem();
//        ManHinh mh = (ManHinh) cboManHinh.getSelectedItem();
//        VGA vga = (VGA) cboVGA.getSelectedItem();
//        MauSac ms = (MauSac) cboMauSac.getSelectedItem();
//
//        SanPham sp = new SanPham();
//        sp.setIdHang(h.getId());
//        sp.setIdCpu(cpu.getId());
//        sp.setIdRam(ram.getId());
//        sp.setIdOCung(oc.getId());
//        sp.setIdVga(vga.getId());
//        sp.setIdManHinh(mh.getId());
//        sp.setIdMauSac(ms.getId());
//        sp.setMa(txtMa.getText());
//        sp.setTen(txt_ten.getText());
//        sp.setGiaNhap(Double.valueOf(txt_gianhap.getText()));
//        sp.setGiaBan(Double.valueOf(txt_giaban.getText()));
//        sp.setSLTon(Integer.parseInt(txtSLTon.getText()));
//        boolean rs = spS.insert(sp);
//        if (rs == true) {
//            JOptionPane.showMessageDialog(this, "Thêm thành công");
//        } else {
//            JOptionPane.showMessageDialog(this, "Thêm thất bại");
//        }
//
//    }
//
//    public void updateSP() {
//        Hang h = (Hang) cboHang.getSelectedItem();
//        CPU cpu = (CPU) cboCPU.getSelectedItem();
//        RAM ram = (RAM) cboRam.getSelectedItem();
//        OCung oc = (OCung) cboOcung.getSelectedItem();
//        ManHinh mh = (ManHinh) cboManHinh.getSelectedItem();
//        VGA vga = (VGA) cboVGA.getSelectedItem();
//        MauSac ms = (MauSac) cboMauSac.getSelectedItem();
//        String ma = txtMa.getText();
//        String ten = txt_ten.getText();
//        double giaN = Double.parseDouble(txt_gianhap.getText());
//        double giaB = Double.parseDouble(txt_giaban.getText());
//        int sl = Integer.parseInt(txtSLTon.getText());
//        int index = tblSanPham.getSelectedRow();
//        listSP = spS.getListSP();
//        SanPham sp = listSP.get(index);
//        SanPham spCheck = spS.getSP(txtMa.getText());
//        if (spCheck == null) {
//            sp = new SanPham(sp.getId(), ms.getId(), h.getId(), ram.getId(), cpu.getId(),
//                    oc.getId(), vga.getId(), mh.getId(), ma, ten, sl, giaN, giaB, 0);
//            boolean rs = spS.update(sp);
//            JOptionPane.showMessageDialog(this, "Cập nhật thành công");
//            fillTB();
//        } else if (sp.getMa().equals(txtMa.getText())) {
//            sp = new SanPham(sp.getId(), ms.getId(), h.getId(), ram.getId(), cpu.getId(),
//                    oc.getId(), vga.getId(), mh.getId(), ma, ten, sl, giaN, giaB, 0);
//            boolean rs = spS.update(sp);
//            JOptionPane.showMessageDialog(this, "Cập nhật thành công");
//            fillTB();
//        } else {
//            JOptionPane.showMessageDialog(this, "Mã sản phẩm đã tồn tại");
//        }
//    }
//
//    private void deleteSP() {
//        int index = tblSanPham.getSelectedRow();
//        SanPhamViewMD sp = listSPV.get(index);
//        boolean result = spS.delete(sp);
//        if (result == true) {
//            fillTB();
//            JOptionPane.showMessageDialog(this, "Xóa thành công");
//        } else {
//            JOptionPane.showMessageDialog(this, "Xóa thất bại");
//        }
//    }
//
//    private boolean checkValidate() {
//        Pattern p = Pattern.compile("[^a-z0-9 ]", Pattern.CASE_INSENSITIVE);
//        Matcher ma = p.matcher(txtMa.getText());
//        Matcher ten = p.matcher(txt_ten.getText());
//
//        if (txtMa.getText().isEmpty()) {
//            JOptionPane.showMessageDialog(this, "Mã không được trống");
//            txtMa.requestFocus();
//            return false;
//        } else if (ma.find()) {
//            JOptionPane.showMessageDialog(this, "Mã không được chứa ký tự đặc biệt");
//            txtMa.requestFocus();
//            return false;
//        }
//
//        if (checkMa(txtMa.getText().trim()) == 1) {
//            JOptionPane.showMessageDialog(this, "Mã sản phẩm đã tồn tại");
//            txtMa.requestFocus();
//            return false;
//        }
//
//        if (txt_ten.getText().isEmpty()) {
//            JOptionPane.showMessageDialog(this, "Tên không được trống");
//            txt_ten.requestFocus();
//            return false;
//        } else if (ten.find()) {
//            JOptionPane.showMessageDialog(this, "Tên không được chứa ký tự đặc biệt");
//            txt_ten.requestFocus();
//            return false;
//        }
//
//        if (txt_gianhap.getText().isEmpty()) {
//            JOptionPane.showMessageDialog(this, "Giá nhập không được trống");
//            txt_giaban.requestFocus();
//            return false;
//        }
//
//        try {
//            double giaNhap = Double.parseDouble(txt_gianhap.getText());
//
//            if (giaNhap <= 0) {
//                JOptionPane.showMessageDialog(this, "Giá nhập phải lớn hơn 0");
//                txt_gianhap.requestFocus();
//                return false;
//            }
//
//        } catch (NumberFormatException e) {
//            JOptionPane.showMessageDialog(this, "Giá bán phải là số");
//            txt_gianhap.requestFocus();
//            return false;
//        }
//
//        if (txt_giaban.getText().isEmpty()) {
//            JOptionPane.showMessageDialog(this, "Giá bán không được trống");
//            txt_giaban.requestFocus();
//            return false;
//        }
//
//        try {
//            double giaBan = Double.parseDouble(txt_giaban.getText());
//
//            if (giaBan <= 0) {
//                JOptionPane.showMessageDialog(this, "Giá bán phải lớn hơn 0");
//                txt_giaban.requestFocus();
//                return false;
//            }
//
//        } catch (NumberFormatException e) {
//            JOptionPane.showMessageDialog(this, "Giá bán phải là số");
//            txt_giaban.requestFocus();
//            return false;
//        }
//
//        if (txtSLTon.getText().isEmpty()) {
//            JOptionPane.showMessageDialog(this, "Số lượng không được trống");
//            txtSLTon.requestFocus();
//            return false;
//        }
//
//        try {
//            int soLuong = Integer.parseInt(txtSLTon.getText());
//
//            if (soLuong <= 0) {
//                JOptionPane.showMessageDialog(this, "Số lượng phải lớn hơn 0");
//                txtSLTon.requestFocus();
//                return false;
//            }
//
//        } catch (NumberFormatException e) {
//            JOptionPane.showMessageDialog(this, "Số lượng phải là số");
//            txtSLTon.requestFocus();
//            return false;
//        }
//        return true;
//    }
//    
//    private boolean checkValidateUpdate() {
//        Pattern p = Pattern.compile("[^a-z0-9 ]", Pattern.CASE_INSENSITIVE);
//        Matcher ma = p.matcher(txtMa.getText());
//        Matcher ten = p.matcher(txt_ten.getText());
//
//        if (txtMa.getText().isEmpty()) {
//            JOptionPane.showMessageDialog(this, "Mã không được trống");
//            txtMa.requestFocus();
//            return false;
//        } else if (ma.find()) {
//            JOptionPane.showMessageDialog(this, "Mã không được chứa ký tự đặc biệt");
//            txtMa.requestFocus();
//            return false;
//        }
//
//        if (txt_ten.getText().isEmpty()) {
//            JOptionPane.showMessageDialog(this, "Tên không được trống");
//            txt_ten.requestFocus();
//            return false;
//        } else if (ten.find()) {
//            JOptionPane.showMessageDialog(this, "Tên không được chứa ký tự đặc biệt");
//            txt_ten.requestFocus();
//            return false;
//        }
//
//        if (txt_gianhap.getText().isEmpty()) {
//            JOptionPane.showMessageDialog(this, "Giá nhập không được trống");
//            txt_giaban.requestFocus();
//            return false;
//        }
//
//        try {
//            double giaNhap = Double.parseDouble(txt_gianhap.getText());
//
//            if (giaNhap <= 0) {
//                JOptionPane.showMessageDialog(this, "Giá nhập phải lớn hơn 0");
//                txt_gianhap.requestFocus();
//                return false;
//            }
//
//        } catch (NumberFormatException e) {
//            JOptionPane.showMessageDialog(this, "Giá bán phải là số");
//            txt_gianhap.requestFocus();
//            return false;
//        }
//
//        if (txt_giaban.getText().isEmpty()) {
//            JOptionPane.showMessageDialog(this, "Giá bán không được trống");
//            txt_giaban.requestFocus();
//            return false;
//        }
//
//        try {
//            double giaBan = Double.parseDouble(txt_giaban.getText());
//
//            if (giaBan <= 0) {
//                JOptionPane.showMessageDialog(this, "Giá bán phải lớn hơn 0");
//                txt_giaban.requestFocus();
//                return false;
//            }
//
//        } catch (NumberFormatException e) {
//            JOptionPane.showMessageDialog(this, "Giá bán phải là số");
//            txt_giaban.requestFocus();
//            return false;
//        }
//
//        if (txtSLTon.getText().isEmpty()) {
//            JOptionPane.showMessageDialog(this, "Số lượng không được trống");
//            txtSLTon.requestFocus();
//            return false;
//        }
//
//        try {
//            int soLuong = Integer.parseInt(txtSLTon.getText());
//
//            if (soLuong <= 0) {
//                JOptionPane.showMessageDialog(this, "Số lượng phải lớn hơn 0");
//                txtSLTon.requestFocus();
//                return false;
//            }
//
//        } catch (NumberFormatException e) {
//            JOptionPane.showMessageDialog(this, "Số lượng phải là số");
//            txtSLTon.requestFocus();
//            return false;
//        }
//        return true;
//    }
//
//    private int checkMa(String ma) {
//        for (int i = 0; i < spS.getListSP().size(); i++) {
//            SanPham get = spS.getListSP().get(i);
//            if (get.getMa().trim().equalsIgnoreCase(ma)) {
//                return 1;
//            }
//        }
//        return 2;
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cpu;
    private javax.swing.JButton btn_hang;
    private javax.swing.JButton btn_manhinh;
    private javax.swing.JButton btn_mausac;
    private javax.swing.JButton btn_moi;
    private javax.swing.JButton btn_ocung;
    private javax.swing.JButton btn_ram;
    private javax.swing.JButton btn_sanpham;
    private javax.swing.JButton btn_sua;
    private javax.swing.JButton btn_them;
    private javax.swing.JButton btn_vga;
    private javax.swing.JButton btn_xoa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cboCPU;
    private javax.swing.JComboBox<String> cboHang;
    private javax.swing.JComboBox<String> cboManHinh;
    private javax.swing.JComboBox<String> cboMauSac;
    private javax.swing.JComboBox<String> cboOcung;
    private javax.swing.JComboBox<String> cboRam;
    private javax.swing.JComboBox<String> cboVGA;
    private javax.swing.JComboBox<String> cbo_sanpham;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JRadioButton rdo_con;
    private javax.swing.JRadioButton rdo_khong;
    private javax.swing.JTable tblSanPham;
    private javax.swing.JTextField txtSLTon;
    private javax.swing.JTextField txt_giaban;
    private javax.swing.JTextField txt_gianhap;
    // End of variables declaration//GEN-END:variables
}
