package View;

import Model.ChiTietSanPham;
import Model.Cpu;
import Model.Hang;
import Model.ManHinh;
import Model.MauSac;
import Model.OCung;
import Model.Ram;
import Model.SanPham;
import Model.Serial;
import Model.Vga;
import Service.CPUService;
import Service.ChiTietSanPhamService;
import Service.HangService;
import Service.ManHinhService;
import Service.MauSacService;
import Service.OCungService;
import Service.RamService;
import Service.SanPhamService;
import Service.SerialService;
import Service.VGAService;
import ViewModel.ChiTietSanPhamModel;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author quyen
 */
public class JPanelSanPham extends javax.swing.JPanel {

    HangService hS = new HangService();
    OCungService ocS = new OCungService();
    RamService rS = new RamService();
    ManHinhService mhS = new ManHinhService();
    VGAService vS = new VGAService();
    CPUService cS = new CPUService();
    MauSacService msS = new MauSacService();
    SanPhamService spS = new SanPhamService();
    SerialService serialService = new SerialService();
    ChiTietSanPhamService ctspService = new ChiTietSanPhamService();

    public JPanelSanPham() {
        initComponents();
        List<Hang> listH = hS.getListHang();
        cbo_hang.setModel(new DefaultComboBoxModel(listH.toArray()));
        List<Cpu> listC = cS.getListCPU();
        cbo_cpu.setModel(new DefaultComboBoxModel(listC.toArray()));
        List<Ram> listR = rS.getAllRam();
        cbo_ram.setModel(new DefaultComboBoxModel(listR.toArray()));
        List<OCung> listO = ocS.getAllOCung();
        cbo_ocung.setModel(new DefaultComboBoxModel(listO.toArray()));
        List<Vga> listV = vS.getListDB();
        cbo_vga.setModel(new DefaultComboBoxModel(listV.toArray()));
        List<ManHinh> listMH = mhS.getListManHinh();
        cbo_manhinh.setModel(new DefaultComboBoxModel(listMH.toArray()));
        List<MauSac> listMS = msS.getAllMauSac();
        cbo_mausac.setModel(new DefaultComboBoxModel(listMS.toArray()));
        List<SanPham> listSP = spS.getAllSanPham();
        cbo_sanpham.setModel(new DefaultComboBoxModel(listSP.toArray()));

        fillSanPham(ctspService.getListSanPham());
        fillSanPhamXoa(ctspService.getListSanPham());

        btn_sua.setEnabled(false);
        btn_xoa.setEnabled(false);
    }

    public void fillComboBox() {
        List<Hang> listH = hS.getListHang();
        cbo_hang.setModel(new DefaultComboBoxModel(listH.toArray()));
        List<Cpu> listC = cS.getListCPU();
        cbo_cpu.setModel(new DefaultComboBoxModel(listC.toArray()));
        List<Ram> listR = rS.getAllRam();
        cbo_ram.setModel(new DefaultComboBoxModel(listR.toArray()));
        List<OCung> listO = ocS.getAllOCung();
        cbo_ocung.setModel(new DefaultComboBoxModel(listO.toArray()));
        List<Vga> listV = vS.getListDB();
        cbo_vga.setModel(new DefaultComboBoxModel(listV.toArray()));
        List<ManHinh> listMH = mhS.getListManHinh();
        cbo_manhinh.setModel(new DefaultComboBoxModel(listMH.toArray()));
        List<MauSac> listMS = msS.getAllMauSac();
        cbo_mausac.setModel(new DefaultComboBoxModel(listMS.toArray()));
        List<SanPham> listSP = spS.getAllSanPham();
        cbo_sanpham.setModel(new DefaultComboBoxModel(listSP.toArray()));

        fillSanPham(ctspService.getListSanPham());
        fillSanPhamXoa(ctspService.getListSanPham());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_sanpham = new javax.swing.JTable();
        cbo_hang = new javax.swing.JComboBox<>();
        btn_hang = new javax.swing.JButton();
        cbo_cpu = new javax.swing.JComboBox<>();
        btn_cpu = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cbo_ram = new javax.swing.JComboBox<>();
        cbo_ocung = new javax.swing.JComboBox<>();
        btn_ram = new javax.swing.JButton();
        btn_ocung = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        cbo_vga = new javax.swing.JComboBox<>();
        btn_vga = new javax.swing.JButton();
        btn_manhinh = new javax.swing.JButton();
        cbo_manhinh = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        btn_mausac = new javax.swing.JButton();
        cbo_mausac = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        btn_sanpham = new javax.swing.JButton();
        cbo_sanpham = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txt_timkiem = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        btn_timkiem = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txt_gianhap = new javax.swing.JTextField();
        txt_giaban = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtSLTon = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        btn_sua = new javax.swing.JButton();
        btn_moi = new javax.swing.JButton();
        btn_them = new javax.swing.JButton();
        btn_xoa = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        rdo_con = new javax.swing.JRadioButton();
        rdo_khong = new javax.swing.JRadioButton();
        cbo_serial = new javax.swing.JComboBox<>();
        btn_serial = new javax.swing.JButton();
        btn_load = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_sanphamxoa = new javax.swing.JTable();
        jLabel16 = new javax.swing.JLabel();
        txt_timkiemspx = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        btn_timkiemspx = new javax.swing.JButton();
        btn_khoiphuc = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(147, 214, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("          Sản Phẩm");
        jLabel2.setOpaque(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1070, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 60));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbl_sanpham.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tbl_sanpham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Sản Phẩm", "Cpu", "Hãng", "Màn Hình", "Màu Sắc", "Ổ cứng", "Ram", "Vga", "Số lượng tồn", "Giá Nhập", "Giá Bán", "Ngày Tạo", "Ngày Nhập", "Trạng Thái"
            }
        ));
        tbl_sanpham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_sanphamMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_sanpham);

        jPanel6.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 19, 1070, 256));

        jPanel6.add(cbo_hang, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 411, 130, -1));

        btn_hang.setBackground(new java.awt.Color(147, 214, 255));
        btn_hang.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_hang.setForeground(new java.awt.Color(255, 255, 255));
        btn_hang.setText("Hãng");
        btn_hang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hangActionPerformed(evt);
            }
        });
        jPanel6.add(btn_hang, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 441, 130, 28));

        jPanel6.add(cbo_cpu, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 411, 130, -1));

        btn_cpu.setBackground(new java.awt.Color(147, 214, 255));
        btn_cpu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_cpu.setForeground(new java.awt.Color(255, 255, 255));
        btn_cpu.setText("CPU");
        btn_cpu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cpuActionPerformed(evt);
            }
        });
        jPanel6.add(btn_cpu, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 441, 130, 28));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("CPU");
        jLabel7.setMaximumSize(new java.awt.Dimension(100, 50));
        jLabel7.setMinimumSize(new java.awt.Dimension(40, 20));
        jLabel7.setPreferredSize(new java.awt.Dimension(40, 20));
        jPanel6.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 381, 32, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Hãng");
        jLabel3.setMaximumSize(new java.awt.Dimension(100, 50));
        jLabel3.setMinimumSize(new java.awt.Dimension(40, 20));
        jLabel3.setPreferredSize(new java.awt.Dimension(40, 20));
        jPanel6.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 381, 32, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("RAM");
        jLabel5.setMinimumSize(new java.awt.Dimension(40, 20));
        jLabel5.setPreferredSize(new java.awt.Dimension(40, 20));
        jPanel6.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 381, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Ổ cứng");
        jPanel6.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 381, -1, -1));

        jPanel6.add(cbo_ram, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 411, 130, -1));

        jPanel6.add(cbo_ocung, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 411, 130, -1));

        btn_ram.setBackground(new java.awt.Color(147, 214, 255));
        btn_ram.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_ram.setForeground(new java.awt.Color(255, 255, 255));
        btn_ram.setText("RAM");
        btn_ram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ramActionPerformed(evt);
            }
        });
        jPanel6.add(btn_ram, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 441, 130, 28));

        btn_ocung.setBackground(new java.awt.Color(147, 214, 255));
        btn_ocung.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_ocung.setForeground(new java.awt.Color(255, 255, 255));
        btn_ocung.setText("Ổ cứng");
        btn_ocung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ocungActionPerformed(evt);
            }
        });
        jPanel6.add(btn_ocung, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 441, 130, 28));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("VGA");
        jLabel4.setMaximumSize(new java.awt.Dimension(100, 50));
        jLabel4.setMinimumSize(new java.awt.Dimension(40, 20));
        jLabel4.setPreferredSize(new java.awt.Dimension(40, 20));
        jPanel6.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 487, 32, -1));

        jPanel6.add(cbo_vga, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 507, 130, -1));

        btn_vga.setBackground(new java.awt.Color(147, 214, 255));
        btn_vga.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_vga.setForeground(new java.awt.Color(255, 255, 255));
        btn_vga.setText("VGA");
        btn_vga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_vgaActionPerformed(evt);
            }
        });
        jPanel6.add(btn_vga, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 537, 130, 28));

        btn_manhinh.setBackground(new java.awt.Color(147, 214, 255));
        btn_manhinh.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_manhinh.setForeground(new java.awt.Color(255, 255, 255));
        btn_manhinh.setText("Màn Hình");
        btn_manhinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_manhinhActionPerformed(evt);
            }
        });
        jPanel6.add(btn_manhinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 537, 130, 28));

        jPanel6.add(cbo_manhinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 507, 130, -1));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Màn hình");
        jLabel9.setMaximumSize(new java.awt.Dimension(100, 50));
        jLabel9.setMinimumSize(new java.awt.Dimension(40, 20));
        jLabel9.setPreferredSize(new java.awt.Dimension(40, 20));
        jPanel6.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 487, 60, -1));

        btn_mausac.setBackground(new java.awt.Color(147, 214, 255));
        btn_mausac.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_mausac.setForeground(new java.awt.Color(255, 255, 255));
        btn_mausac.setText("Màu Sắc");
        btn_mausac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mausacActionPerformed(evt);
            }
        });
        jPanel6.add(btn_mausac, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 537, 130, 28));

        jPanel6.add(cbo_mausac, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 507, 130, -1));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Màu sắc");
        jLabel10.setMaximumSize(new java.awt.Dimension(100, 50));
        jLabel10.setMinimumSize(new java.awt.Dimension(40, 20));
        jLabel10.setPreferredSize(new java.awt.Dimension(40, 20));
        jPanel6.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 487, 60, -1));

        btn_sanpham.setBackground(new java.awt.Color(147, 214, 255));
        btn_sanpham.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_sanpham.setForeground(new java.awt.Color(255, 255, 255));
        btn_sanpham.setText("Sản Phẩm");
        btn_sanpham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sanphamActionPerformed(evt);
            }
        });
        jPanel6.add(btn_sanpham, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 537, 130, 28));

        jPanel6.add(cbo_sanpham, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 507, 130, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Sản phẩm");
        jLabel8.setMaximumSize(new java.awt.Dimension(100, 50));
        jLabel8.setMinimumSize(new java.awt.Dimension(40, 20));
        jLabel8.setPreferredSize(new java.awt.Dimension(40, 20));
        jPanel6.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 487, 60, -1));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setText("Tìm kiếm");
        jPanel6.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 305, -1, -1));

        txt_timkiem.setBorder(null);
        txt_timkiem.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel6.add(txt_timkiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 323, 160, 20));

        jSeparator2.setForeground(new java.awt.Color(147, 214, 255));
        jPanel6.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 343, 160, 10));

        btn_timkiem.setBackground(new java.awt.Color(147, 214, 255));
        btn_timkiem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_timkiem.setForeground(new java.awt.Color(255, 255, 255));
        btn_timkiem.setText("Tìm kiếm");
        btn_timkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_timkiemActionPerformed(evt);
            }
        });
        jPanel6.add(btn_timkiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 323, -1, -1));

        jLabel11.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel11.setText("Giá bán");
        jPanel6.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 340, 50, 20));

        jLabel13.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel13.setText("Trạng Thái");
        jPanel6.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 470, 70, 20));

        txt_gianhap.setBorder(null);
        jPanel6.add(txt_gianhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 360, 130, 20));

        txt_giaban.setBorder(null);
        jPanel6.add(txt_giaban, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 360, 130, 20));

        jLabel14.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel14.setText("Giá nhập");
        jPanel6.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 340, 80, 20));

        jSeparator1.setForeground(new java.awt.Color(147, 214, 255));
        jPanel6.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 450, 130, 10));

        txtSLTon.setEditable(false);
        txtSLTon.setBackground(new java.awt.Color(255, 255, 255));
        txtSLTon.setBorder(null);
        jPanel6.add(txtSLTon, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 430, 130, 20));

        jSeparator4.setForeground(new java.awt.Color(147, 214, 255));
        jPanel6.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 380, 130, 10));

        jSeparator5.setForeground(new java.awt.Color(147, 214, 255));
        jPanel6.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 380, 130, 10));

        btn_sua.setBackground(new java.awt.Color(147, 214, 255));
        btn_sua.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_sua.setForeground(new java.awt.Color(255, 255, 255));
        btn_sua.setText("Sửa");
        btn_sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_suaActionPerformed(evt);
            }
        });
        jPanel6.add(btn_sua, new org.netbeans.lib.awtextra.AbsoluteConstraints(807, 533, 70, 32));

        btn_moi.setBackground(new java.awt.Color(147, 214, 255));
        btn_moi.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_moi.setForeground(new java.awt.Color(255, 255, 255));
        btn_moi.setText("Mới");
        btn_moi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_moiActionPerformed(evt);
            }
        });
        jPanel6.add(btn_moi, new org.netbeans.lib.awtextra.AbsoluteConstraints(977, 533, 70, 32));

        btn_them.setBackground(new java.awt.Color(147, 214, 255));
        btn_them.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_them.setForeground(new java.awt.Color(255, 255, 255));
        btn_them.setText("Thêm");
        btn_them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themActionPerformed(evt);
            }
        });
        jPanel6.add(btn_them, new org.netbeans.lib.awtextra.AbsoluteConstraints(717, 533, 70, 32));

        btn_xoa.setBackground(new java.awt.Color(147, 214, 255));
        btn_xoa.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_xoa.setForeground(new java.awt.Color(255, 255, 255));
        btn_xoa.setText("Xóa");
        btn_xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoaActionPerformed(evt);
            }
        });
        jPanel6.add(btn_xoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(897, 533, 70, 32));

        jLabel15.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel15.setText("Số lượng tồn");
        jPanel6.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 410, 90, 20));

        buttonGroup1.add(rdo_con);
        rdo_con.setSelected(true);
        rdo_con.setText("Còn");
        jPanel6.add(rdo_con, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 490, -1, -1));

        buttonGroup1.add(rdo_khong);
        rdo_khong.setText("Không");
        jPanel6.add(rdo_khong, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 490, 60, -1));

        jPanel6.add(cbo_serial, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 410, 130, -1));

        btn_serial.setBackground(new java.awt.Color(147, 214, 255));
        btn_serial.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_serial.setForeground(new java.awt.Color(255, 255, 255));
        btn_serial.setText("Serial");
        btn_serial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_serialActionPerformed(evt);
            }
        });
        jPanel6.add(btn_serial, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 440, 130, 30));

        btn_load.setBackground(new java.awt.Color(147, 214, 255));
        btn_load.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_load.setForeground(new java.awt.Color(255, 255, 255));
        btn_load.setText("Load");
        btn_load.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loadActionPerformed(evt);
            }
        });
        jPanel6.add(btn_load, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 290, 60, 30));

        jTabbedPane1.addTab("Sản Phẩm", jPanel6);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        tbl_sanphamxoa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Sản phẩm", "Cpu", "Hãng", "Màn hình", "Màu sắc", "Ổ cứng", "Ram", "Vga", "Số lượng tồn", "Giá nhập", "Giá bán", "Ngày tạo", "Ngày nhập", "Trạng thái"
            }
        ));
        jScrollPane2.setViewportView(tbl_sanphamxoa);

        jLabel16.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel16.setText("Tìm kiếm");

        txt_timkiemspx.setBorder(null);
        txt_timkiemspx.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jSeparator3.setForeground(new java.awt.Color(147, 214, 255));

        btn_timkiemspx.setBackground(new java.awt.Color(147, 214, 255));
        btn_timkiemspx.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_timkiemspx.setForeground(new java.awt.Color(255, 255, 255));
        btn_timkiemspx.setText("Tìm kiếm");
        btn_timkiemspx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_timkiemspxActionPerformed(evt);
            }
        });

        btn_khoiphuc.setBackground(new java.awt.Color(147, 214, 255));
        btn_khoiphuc.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_khoiphuc.setForeground(new java.awt.Color(255, 255, 255));
        btn_khoiphuc.setText("Khôi Phục");
        btn_khoiphuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_khoiphucActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_timkiemspx, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addComponent(btn_timkiemspx)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 584, Short.MAX_VALUE)
                        .addComponent(btn_khoiphuc)
                        .addGap(87, 87, 87))))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel16)
                .addGap(4, 4, 4)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(txt_timkiemspx, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_timkiemspx)
                        .addComponent(btn_khoiphuc, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Ngừng bán", jPanel7);

        jPanel2.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 620));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 1070, 620));
    }// </editor-fold>//GEN-END:initComponents

    private void tbl_sanphamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_sanphamMouseClicked
        btn_them.setEnabled(false);
        btn_sua.setEnabled(true);
        btn_xoa.setEnabled(true);

        int index = tbl_sanpham.getSelectedRow();
        cbo_sanpham.setSelectedItem(findSanPhamByName(tbl_sanpham.getModel().getValueAt(index, 1).toString()));
        cbo_cpu.setSelectedItem(findCpuByName(tbl_sanpham.getModel().getValueAt(index, 2).toString()));
        cbo_hang.setSelectedItem(findHangByName(tbl_sanpham.getModel().getValueAt(index, 3).toString()));
        cbo_manhinh.setSelectedItem(findManHinhByName(tbl_sanpham.getModel().getValueAt(index, 4).toString()));
        cbo_mausac.setSelectedItem(findMauSacByName(tbl_sanpham.getModel().getValueAt(index, 5).toString()));
        cbo_ocung.setSelectedItem(findOcungByName(tbl_sanpham.getModel().getValueAt(index, 6).toString()));
        cbo_ram.setSelectedItem(findRamByName(tbl_sanpham.getModel().getValueAt(index, 7).toString()));
        cbo_vga.setSelectedItem(findVgaByName(tbl_sanpham.getModel().getValueAt(index, 8).toString()));
        txtSLTon.setText(tbl_sanpham.getValueAt(index, 9).toString());
        txt_gianhap.setText(tbl_sanpham.getValueAt(index, 10).toString());
        txt_giaban.setText(tbl_sanpham.getValueAt(index, 11).toString());
        if (tbl_sanpham.getValueAt(index, 14).toString().equalsIgnoreCase("Còn bán")) {
            rdo_con.setSelected(true);
        } else {
            rdo_khong.setSelected(true);
        }

        List<Serial> listSeri = serialService.getSerialByIdCTSP(Integer.parseInt(tbl_sanpham.getValueAt(index, 0).toString()));
        cbo_serial.setModel(new DefaultComboBoxModel(listSeri.toArray()));
    }//GEN-LAST:event_tbl_sanphamMouseClicked

    private void btn_timkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_timkiemActionPerformed
        if (txt_timkiem.getText().equals("")) {
            fillSanPham(ctspService.getListSanPham());
        }
        fillSanPham(ctspService.timKiem(txt_timkiem.getText()));
    }//GEN-LAST:event_btn_timkiemActionPerformed

    private void btn_hangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hangActionPerformed
        CRUDhang hang = new CRUDhang();
        hang.setVisible(true);
    }//GEN-LAST:event_btn_hangActionPerformed

    private void btn_cpuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cpuActionPerformed
        CRUDcpu cpu = new CRUDcpu();
        cpu.setVisible(true);
    }//GEN-LAST:event_btn_cpuActionPerformed

    private void btn_ramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ramActionPerformed
        CRUDram ram = new CRUDram();
        ram.setVisible(true);
    }//GEN-LAST:event_btn_ramActionPerformed

    private void btn_ocungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ocungActionPerformed
        CRUDocung ocung = new CRUDocung();
        ocung.setVisible(true);
    }//GEN-LAST:event_btn_ocungActionPerformed

    private void btn_vgaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_vgaActionPerformed
        CRUDvga vga = new CRUDvga();
        vga.setVisible(true);
    }//GEN-LAST:event_btn_vgaActionPerformed

    private void btn_manhinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_manhinhActionPerformed
        CRUDmanhinh manhinh = new CRUDmanhinh();
        manhinh.setVisible(true);
    }//GEN-LAST:event_btn_manhinhActionPerformed

    private void btn_mausacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mausacActionPerformed
        CRUDmausac mausac = new CRUDmausac();
        mausac.setVisible(true);
    }//GEN-LAST:event_btn_mausacActionPerformed

    private void btn_sanphamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sanphamActionPerformed
        CRUDsanpham sanpham = new CRUDsanpham();
        sanpham.setVisible(true);
    }//GEN-LAST:event_btn_sanphamActionPerformed

    private void btn_themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themActionPerformed
        int cf = JOptionPane.showConfirmDialog(this, "Bạn có muốn thêm không?", "Thêm", JOptionPane.YES_NO_OPTION);

        String hang = cbo_hang.getSelectedItem().toString();
        String cpu = cbo_cpu.getSelectedItem().toString();
        String ram = cbo_ram.getSelectedItem().toString();
        String ocung = cbo_ocung.getSelectedItem().toString();
        String manhinh = cbo_manhinh.getSelectedItem().toString();
        String vga = cbo_vga.getSelectedItem().toString();
        String ms = cbo_mausac.getSelectedItem().toString();
        String sp = cbo_sanpham.getSelectedItem().toString();

        if (checkTrung(sp, cpu, hang, manhinh, ms, ocung, ram, vga) == 1) {
            JOptionPane.showMessageDialog(this, "Sản phẩm đã tồn tại");
            return;
        }
        if (checkValidate()) {
            if (cf == JOptionPane.YES_OPTION) {
                JOptionPane.showMessageDialog(this, ctspService.insert(getFieldInsert()));
                fillSanPham(ctspService.getListSanPham());
            }
        }
    }//GEN-LAST:event_btn_themActionPerformed

    private void btn_suaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_suaActionPerformed
        int cf = JOptionPane.showConfirmDialog(this, "Bạn có muốn sửa không?", "Sửa", JOptionPane.YES_NO_OPTION);

        if (checkValidate()) {
            if (cf == JOptionPane.YES_OPTION) {
                JOptionPane.showMessageDialog(this, ctspService.update(getFieldUpdate()));
                fillSanPham(ctspService.getListSanPham());
                btn_them.setEnabled(true);
                btn_sua.setEnabled(false);
                btn_xoa.setEnabled(false);
            }
        }
    }//GEN-LAST:event_btn_suaActionPerformed

    private void btn_xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoaActionPerformed
        int index = tbl_sanpham.getSelectedRow();

        int cf = JOptionPane.showConfirmDialog(this, "Bạn có muốn xóa không?", "Xóa", JOptionPane.YES_NO_OPTION);
        ChiTietSanPham ctsp = new ChiTietSanPham();
        ctsp.setId(Integer.parseInt(tbl_sanpham.getValueAt(index, 0).toString()));
        ctsp.setTrangThai(1);

        if (cf == JOptionPane.YES_OPTION) {
            boolean result = ctspService.updateTT(ctsp);
            if (result) {
                JOptionPane.showMessageDialog(this, "Xóa sản phẩm thành công");
            } else {
                JOptionPane.showMessageDialog(this, "Xóa sản phẩm thất bại");
            }
            fillSanPham(ctspService.getListSanPham());
            fillSanPhamXoa(ctspService.getListSanPham());
            btn_them.setEnabled(true);
            btn_sua.setEnabled(false);
            btn_xoa.setEnabled(false);
        }
    }//GEN-LAST:event_btn_xoaActionPerformed

    private void btn_moiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_moiActionPerformed
        txtSLTon.setText("");
        txt_gianhap.setText("");
        txt_giaban.setText("");
        btn_them.setEnabled(true);
        btn_sua.setEnabled(false);
        btn_xoa.setEnabled(false);
    }//GEN-LAST:event_btn_moiActionPerformed

    private void btn_timkiemspxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_timkiemspxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_timkiemspxActionPerformed

    private void btn_khoiphucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_khoiphucActionPerformed
        int index = tbl_sanphamxoa.getSelectedRow();

        if (index == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn sản phẩm để khôi phục");
            return;
        }

        int cf = JOptionPane.showConfirmDialog(this, "Bạn có muốn khôi phục không?", "Khôi phục", JOptionPane.YES_NO_OPTION);
        ChiTietSanPham ctsp = new ChiTietSanPham();
        ctsp.setId(Integer.parseInt(tbl_sanphamxoa.getValueAt(index, 0).toString()));
        ctsp.setTrangThai(0);
        if (cf == JOptionPane.YES_OPTION) {
            boolean result = ctspService.updateTT(ctsp);
            if (result) {
                JOptionPane.showMessageDialog(this, "Khôi phục sản phẩm thành công");
            } else {
                JOptionPane.showMessageDialog(this, "Khôi phục sản phẩm thất bại");
            }
            fillSanPham(ctspService.getListSanPham());
            fillSanPhamXoa(ctspService.getListSanPham());
        }
    }//GEN-LAST:event_btn_khoiphucActionPerformed

    private void btn_serialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_serialActionPerformed
        int index = tbl_sanpham.getSelectedRow();
        if (index == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn 1 sản phẩm");
            return;
        }
        CRUDserial crud = new CRUDserial(Integer.parseInt(tbl_sanpham.getValueAt(index, 0).toString()));
        crud.setVisible(true);
    }//GEN-LAST:event_btn_serialActionPerformed

    private void btn_loadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loadActionPerformed
        fillComboBox();
    }//GEN-LAST:event_btn_loadActionPerformed

    private void fillSanPham(List<ChiTietSanPhamModel> list) {
        DefaultTableModel mol = (DefaultTableModel) tbl_sanpham.getModel();
        mol.setRowCount(0);
        String tt;
        for (ChiTietSanPhamModel sp : list) {
            if (sp.getTrangThai() == 0) {
                tt = "Còn bán";
                mol.addRow(new Object[]{sp.getId(), sp.getSanPham(), sp.getCpu(), sp.getHang(), sp.getManHinh(), sp.getMauSac(),
                    sp.getoCung(), sp.getRam(), sp.getVga(), sp.getSlTon(), sp.getGiaNhap(), sp.getGiaBan(), sp.getNgayTao(), sp.getNgayNhap(), tt});
            }
        }
    }

    private void fillSanPhamXoa(List<ChiTietSanPhamModel> list) {
        DefaultTableModel mol = (DefaultTableModel) tbl_sanphamxoa.getModel();
        mol.setRowCount(0);
        String tt;
        for (ChiTietSanPhamModel sp : list) {
            if (sp.getTrangThai() == 1) {
                tt = "Ngừng bán";
                mol.addRow(new Object[]{sp.getId(), sp.getSanPham(), sp.getCpu(), sp.getHang(), sp.getManHinh(), sp.getMauSac(),
                    sp.getoCung(), sp.getRam(), sp.getVga(), sp.getSlTon(), sp.getGiaNhap(), sp.getGiaBan(), sp.getNgayTao(), sp.getNgayNhap(), tt});
            }
        }
    }

    private ChiTietSanPham getFieldInsert() {
        ChiTietSanPham ctsp = new ChiTietSanPham();
        LocalDate date = LocalDate.now();
        Hang h = (Hang) cbo_hang.getSelectedItem();
        Cpu cpu = (Cpu) cbo_cpu.getSelectedItem();
        Ram ram = (Ram) cbo_ram.getSelectedItem();
        OCung oc = (OCung) cbo_ocung.getSelectedItem();
        ManHinh mh = (ManHinh) cbo_manhinh.getSelectedItem();
        Vga vga = (Vga) cbo_vga.getSelectedItem();
        MauSac ms = (MauSac) cbo_mausac.getSelectedItem();
        SanPham sp = (SanPham) cbo_sanpham.getSelectedItem();

        ctsp.setIdSanPham(sp.getId());
        ctsp.setIdHang(h.getId());
        ctsp.setIdCpu(cpu.getId());
        ctsp.setIdRam(ram.getId());
        ctsp.setIdOCung(oc.getId());
        ctsp.setIdVga(vga.getId());
        ctsp.setIdManHinh(mh.getId());
        ctsp.setIdMauSac(ms.getId());
        ctsp.setGiaNhap(Double.valueOf(txt_gianhap.getText()));
        ctsp.setGiaBan(Double.valueOf(txt_giaban.getText()));
        ctsp.setNgayTao(date.format(DateTimeFormatter.ISO_DATE));
        ctsp.setNgayNhap(date.format(DateTimeFormatter.ISO_DATE));
        ctsp.setSlTon(0);
        if (rdo_con.isSelected()) {
            ctsp.setTrangThai(0);
        } else {
            ctsp.setTrangThai(1);
        }

        return ctsp;
    }

    private ChiTietSanPham getFieldUpdate() {
        int index = tbl_sanpham.getSelectedRow();
        ChiTietSanPham ctsp = new ChiTietSanPham();
        LocalDate date = LocalDate.now();
        Hang h = (Hang) cbo_hang.getSelectedItem();
        Cpu cpu = (Cpu) cbo_cpu.getSelectedItem();
        Ram ram = (Ram) cbo_ram.getSelectedItem();
        OCung oc = (OCung) cbo_ocung.getSelectedItem();
        ManHinh mh = (ManHinh) cbo_manhinh.getSelectedItem();
        Vga vga = (Vga) cbo_vga.getSelectedItem();
        MauSac ms = (MauSac) cbo_mausac.getSelectedItem();
        SanPham sp = (SanPham) cbo_sanpham.getSelectedItem();

        ctsp.setId(Integer.parseInt(tbl_sanpham.getValueAt(index, 0).toString()));
        ctsp.setIdSanPham(sp.getId());
        ctsp.setIdHang(h.getId());
        ctsp.setIdCpu(cpu.getId());
        ctsp.setIdRam(ram.getId());
        ctsp.setIdOCung(oc.getId());
        ctsp.setIdVga(vga.getId());
        ctsp.setIdManHinh(mh.getId());
        ctsp.setIdMauSac(ms.getId());
        ctsp.setGiaNhap(Double.valueOf(txt_gianhap.getText()));
        ctsp.setGiaBan(Double.valueOf(txt_giaban.getText()));
        ctsp.setNgayNhap(date.format(DateTimeFormatter.ISO_DATE));
        if (rdo_con.isSelected()) {
            ctsp.setTrangThai(0);
        } else {
            ctsp.setTrangThai(1);
        }

        return ctsp;
    }

    private Hang findHangByName(String hangName) {
        for (int i = 0; i < hS.getListHang().size(); i++) {
            Hang hang = cbo_hang.getItemAt(i);
            if (hangName.equalsIgnoreCase(hang.getTen().trim())) {
                return hang;
            }
        }
        return null;
    }

    private Cpu findCpuByName(String categoryName) {
        for (int i = 0; i < hS.getListHang().size(); i++) {
            Cpu cpu = cbo_cpu.getItemAt(i);
            if (categoryName.equalsIgnoreCase(cpu.getTen().trim())) {
                return cpu;
            }
        }
        return null;
    }

    private Ram findRamByName(String ramName) {
        for (int i = 0; i < hS.getListHang().size(); i++) {
            Ram ram = cbo_ram.getItemAt(i);
            if (ramName.equalsIgnoreCase(ram.getTen().trim())) {
                return ram;
            }
        }
        return null;
    }

    private OCung findOcungByName(String ocungName) {
        for (int i = 0; i < hS.getListHang().size(); i++) {
            OCung ocung = cbo_ocung.getItemAt(i);
            if (ocungName.equalsIgnoreCase(ocung.getTen().trim())) {
                return ocung;
            }
        }
        return null;
    }

    private Vga findVgaByName(String vgaName) {
        for (int i = 0; i < hS.getListHang().size(); i++) {
            Vga vga = cbo_vga.getItemAt(i);
            if (vgaName.equalsIgnoreCase(vga.getTen().trim())) {
                return vga;
            }
        }
        return null;
    }

    private ManHinh findManHinhByName(String manHinhName) {
        for (int i = 0; i < hS.getListHang().size(); i++) {
            ManHinh manHinh = cbo_manhinh.getItemAt(i);
            if (manHinhName.equalsIgnoreCase(manHinh.getTen().trim())) {
                return manHinh;
            }
        }
        return null;
    }

    private MauSac findMauSacByName(String mauSacName) {
        for (int i = 0; i < hS.getListHang().size(); i++) {
            MauSac mauSac = cbo_mausac.getItemAt(i);
            if (mauSacName.equalsIgnoreCase(mauSac.getTen().trim())) {
                return mauSac;
            }
        }
        return null;
    }

    private SanPham findSanPhamByName(String sanPhamName) {
        for (int i = 0; i < hS.getListHang().size(); i++) {
            SanPham sanPham = cbo_sanpham.getItemAt(i);
            if (sanPhamName.equalsIgnoreCase(sanPham.getTen().trim())) {
                return sanPham;
            }
        }
        return null;
    }

    private int checkTrung(String sp, String cpu, String hang, String manhinh, String ms, String ocung, String ram, String vga) {
        for (ChiTietSanPhamModel ctspm : ctspService.getListSanPham()) {
            if (ctspm.getSanPham().trim().equalsIgnoreCase(sp) && ctspm.getCpu().trim().equalsIgnoreCase(cpu)
                    && ctspm.getHang().trim().equalsIgnoreCase(hang) && ctspm.getManHinh().trim().equalsIgnoreCase(manhinh)
                    && ctspm.getMauSac().trim().equalsIgnoreCase(ms) && ctspm.getoCung().trim().equalsIgnoreCase(ocung)
                    && ctspm.getRam().trim().equalsIgnoreCase(ram) && ctspm.getVga().trim().equalsIgnoreCase(vga)) {
                return 1;
            }
        }
        return 0;
    }

    private boolean checkValidate() {

        if (txt_gianhap.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Giá nhập không được trống");
            txt_gianhap.requestFocus();
            return false;
        }

        try {
            double giaNhap = Double.parseDouble(txt_gianhap.getText());

            if (giaNhap <= 0) {
                JOptionPane.showMessageDialog(this, "Giá nhập phải lớn hơn 0");
                txt_gianhap.requestFocus();
                return false;
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Giá nhập phải là số");
            txt_gianhap.requestFocus();
            return false;
        }

        if (txt_giaban.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Giá bán không được trống");
            txt_giaban.requestFocus();
            return false;
        }

        try {
            double giaBan = Double.parseDouble(txt_giaban.getText());

            if (giaBan <= 0) {
                JOptionPane.showMessageDialog(this, "Giá bán phải lớn hơn 0");
                txt_giaban.requestFocus();
                return false;
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Giá bán phải là số");
            txt_giaban.requestFocus();
            return false;
        }

        return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cpu;
    private javax.swing.JButton btn_hang;
    private javax.swing.JButton btn_khoiphuc;
    private javax.swing.JButton btn_load;
    private javax.swing.JButton btn_manhinh;
    private javax.swing.JButton btn_mausac;
    private javax.swing.JButton btn_moi;
    private javax.swing.JButton btn_ocung;
    private javax.swing.JButton btn_ram;
    private javax.swing.JButton btn_sanpham;
    private javax.swing.JButton btn_serial;
    private javax.swing.JButton btn_sua;
    private javax.swing.JButton btn_them;
    private javax.swing.JButton btn_timkiem;
    private javax.swing.JButton btn_timkiemspx;
    private javax.swing.JButton btn_vga;
    private javax.swing.JButton btn_xoa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<Cpu> cbo_cpu;
    private javax.swing.JComboBox<Hang> cbo_hang;
    private javax.swing.JComboBox<ManHinh> cbo_manhinh;
    private javax.swing.JComboBox<MauSac> cbo_mausac;
    private javax.swing.JComboBox<OCung> cbo_ocung;
    private javax.swing.JComboBox<Ram> cbo_ram;
    private javax.swing.JComboBox<SanPham> cbo_sanpham;
    private javax.swing.JComboBox<String> cbo_serial;
    private javax.swing.JComboBox<Vga> cbo_vga;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JRadioButton rdo_con;
    private javax.swing.JRadioButton rdo_khong;
    private javax.swing.JTable tbl_sanpham;
    private javax.swing.JTable tbl_sanphamxoa;
    private javax.swing.JTextField txtSLTon;
    private javax.swing.JTextField txt_giaban;
    private javax.swing.JTextField txt_gianhap;
    private javax.swing.JTextField txt_timkiem;
    private javax.swing.JTextField txt_timkiemspx;
    // End of variables declaration//GEN-END:variables
}
