/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import java.awt.Color;
import java.awt.Component;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author quyen
 */
public class mainForm extends javax.swing.JFrame {

    int role = 1;

    public mainForm() {
        initComponents();
        date();
        new Thread() {
            public void run() {
                while (true) {
                    Date date = new Date();
                    SimpleDateFormat dateFormat = new SimpleDateFormat("hh:mm:ss a");
                    lbl_time.setText(dateFormat.format(date));
                }
            }
        }.start();

    }

    public mainForm(String username, int role) {
        initComponents();
        txt_nhanvien.setText(username);
        this.role = role;
        date();
        new Thread() {
            @Override
            public void run() {
                while (true) {
                    Date date = new Date();
                    SimpleDateFormat dateFormat = new SimpleDateFormat("hh:mm:ss a");
                    lbl_time.setText(dateFormat.format(date));
                }
            }
        }.start();
    }

    private void date() {
        DateTimeFormatter dateTimeFormatter = DateTimeFormatter.ofPattern("dd-MM-yyyy");
        LocalDateTime dateTime = LocalDateTime.now();
        lbl_date.setText(dateTimeFormatter.format(dateTime));
    }

    private void showForm(Component component) {
        pnlCard1.removeAll();
        pnlCard1.add(component);
        pnlCard1.revalidate();
        pnlCard1.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btn_sell = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        btn_product = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btn_staff = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        btn_customer = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        btn_report = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        btn_promotion = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        btn_receipt = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lbl_time = new javax.swing.JLabel();
        lbl_date = new javax.swing.JLabel();
        txt_nhanvien = new javax.swing.JLabel();
        btn_doimatkhau = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        btn_dangxuat = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        pnlCard3 = new javax.swing.JPanel();
        pnlCard1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pnlCard4 = new javax.swing.JPanel();
        pnlCard5 = new javax.swing.JPanel();
        pnlCard6 = new javax.swing.JPanel();
        pnlCard7 = new javax.swing.JPanel();
        pnlCard8 = new javax.swing.JPanel();
        pnlCard2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("mainForm"); // NOI18N

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 153, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_sell.setBackground(new java.awt.Color(0, 153, 255));
        btn_sell.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_sell.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_sellMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_sellMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_sellMouseExited(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(102, 102, 102));

        jLabel32.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("Bán hàng");

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cart.png"))); // NOI18N

        javax.swing.GroupLayout btn_sellLayout = new javax.swing.GroupLayout(btn_sell);
        btn_sell.setLayout(btn_sellLayout);
        btn_sellLayout.setHorizontalGroup(
            btn_sellLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_sellLayout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel32)
                .addGap(46, 46, 46))
        );
        btn_sellLayout.setVerticalGroup(
            btn_sellLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_sellLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(btn_sellLayout.createSequentialGroup()
                .addGroup(btn_sellLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(btn_sellLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel32)))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel2.add(btn_sell, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 180, 50));

        btn_product.setBackground(new java.awt.Color(0, 153, 255));
        btn_product.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_product.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_productMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_productMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_productMouseExited(evt);
            }
        });

        jLabel8.setBackground(new java.awt.Color(102, 102, 102));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Sản Phẩm");

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/laptop.png"))); // NOI18N

        javax.swing.GroupLayout btn_productLayout = new javax.swing.GroupLayout(btn_product);
        btn_product.setLayout(btn_productLayout);
        btn_productLayout.setHorizontalGroup(
            btn_productLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_productLayout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addGap(43, 43, 43))
        );
        btn_productLayout.setVerticalGroup(
            btn_productLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_productLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(btn_productLayout.createSequentialGroup()
                .addGroup(btn_productLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(btn_productLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel9)))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel2.add(btn_product, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 180, 50));

        btn_staff.setBackground(new java.awt.Color(0, 153, 255));
        btn_staff.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_staff.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_staffMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_staffMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_staffMouseExited(evt);
            }
        });

        jLabel11.setBackground(new java.awt.Color(102, 102, 102));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Nhân Viên");

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/client.png"))); // NOI18N

        javax.swing.GroupLayout btn_staffLayout = new javax.swing.GroupLayout(btn_staff);
        btn_staff.setLayout(btn_staffLayout);
        btn_staffLayout.setHorizontalGroup(
            btn_staffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_staffLayout.createSequentialGroup()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addGap(41, 41, 41))
        );
        btn_staffLayout.setVerticalGroup(
            btn_staffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_staffLayout.createSequentialGroup()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_staffLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(14, 14, 14))
            .addGroup(btn_staffLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.add(btn_staff, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 180, 50));

        btn_customer.setBackground(new java.awt.Color(0, 153, 255));
        btn_customer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_customer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_customerMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_customerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_customerMouseExited(evt);
            }
        });

        jLabel14.setBackground(new java.awt.Color(102, 102, 102));

        jLabel33.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("Khách Hàng");

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/staff2.png"))); // NOI18N

        javax.swing.GroupLayout btn_customerLayout = new javax.swing.GroupLayout(btn_customer);
        btn_customer.setLayout(btn_customerLayout);
        btn_customerLayout.setHorizontalGroup(
            btn_customerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_customerLayout.createSequentialGroup()
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel33)
                .addGap(29, 29, 29))
        );
        btn_customerLayout.setVerticalGroup(
            btn_customerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_customerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(btn_customerLayout.createSequentialGroup()
                .addGroup(btn_customerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(btn_customerLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel33)))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel2.add(btn_customer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 180, 50));

        btn_report.setBackground(new java.awt.Color(0, 153, 255));
        btn_report.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_report.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_reportMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_reportMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_reportMouseExited(evt);
            }
        });

        jLabel17.setBackground(new java.awt.Color(102, 102, 102));

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Doanh Thu");

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/report2.png"))); // NOI18N

        javax.swing.GroupLayout btn_reportLayout = new javax.swing.GroupLayout(btn_report);
        btn_report.setLayout(btn_reportLayout);
        btn_reportLayout.setHorizontalGroup(
            btn_reportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_reportLayout.createSequentialGroup()
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(jLabel18)
                .addGap(37, 37, 37))
        );
        btn_reportLayout.setVerticalGroup(
            btn_reportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_reportLayout.createSequentialGroup()
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_reportLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel18)
                .addGap(14, 14, 14))
            .addGroup(btn_reportLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.add(btn_report, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 180, 50));

        btn_promotion.setBackground(new java.awt.Color(0, 153, 255));
        btn_promotion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_promotion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_promotionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_promotionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_promotionMouseExited(evt);
            }
        });

        jLabel21.setBackground(new java.awt.Color(102, 102, 102));

        jLabel31.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("Khuyến Mãi");

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/promotion.png"))); // NOI18N

        javax.swing.GroupLayout btn_promotionLayout = new javax.swing.GroupLayout(btn_promotion);
        btn_promotion.setLayout(btn_promotionLayout);
        btn_promotionLayout.setHorizontalGroup(
            btn_promotionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_promotionLayout.createSequentialGroup()
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel31)
                .addGap(30, 30, 30))
        );
        btn_promotionLayout.setVerticalGroup(
            btn_promotionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_promotionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(btn_promotionLayout.createSequentialGroup()
                .addGroup(btn_promotionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(btn_promotionLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel31)))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel2.add(btn_promotion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 180, 50));

        btn_receipt.setBackground(new java.awt.Color(0, 153, 255));
        btn_receipt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_receipt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_receiptMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_receiptMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_receiptMouseExited(evt);
            }
        });

        jLabel15.setBackground(new java.awt.Color(102, 102, 102));

        jLabel34.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("Hóa Đơn");

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/receipt.png"))); // NOI18N

        javax.swing.GroupLayout btn_receiptLayout = new javax.swing.GroupLayout(btn_receipt);
        btn_receipt.setLayout(btn_receiptLayout);
        btn_receiptLayout.setHorizontalGroup(
            btn_receiptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_receiptLayout.createSequentialGroup()
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel34)
                .addGap(52, 52, 52))
        );
        btn_receiptLayout.setVerticalGroup(
            btn_receiptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_receiptLayout.createSequentialGroup()
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_receiptLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel34)
                .addGap(14, 14, 14))
            .addGroup(btn_receiptLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.add(btn_receipt, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 180, 50));

        jLabel23.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("Laptop World");
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 130, -1));

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 130, 10));

        lbl_time.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl_time.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(lbl_time, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 670, 90, 20));

        lbl_date.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl_date.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(lbl_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 670, 80, 20));

        txt_nhanvien.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_nhanvien.setForeground(new java.awt.Color(147, 214, 255));
        txt_nhanvien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/laptop_1.png"))); // NOI18N
        jPanel2.add(txt_nhanvien, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 95, 70));

        btn_doimatkhau.setBackground(new java.awt.Color(0, 153, 255));
        btn_doimatkhau.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_doimatkhau.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_doimatkhauMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_doimatkhauMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_doimatkhauMouseExited(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Đổi Mật Khẩu");

        jLabel6.setBackground(new java.awt.Color(102, 102, 102));

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/key.png"))); // NOI18N

        javax.swing.GroupLayout btn_doimatkhauLayout = new javax.swing.GroupLayout(btn_doimatkhau);
        btn_doimatkhau.setLayout(btn_doimatkhauLayout);
        btn_doimatkhauLayout.setHorizontalGroup(
            btn_doimatkhauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_doimatkhauLayout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(18, 18, 18))
        );
        btn_doimatkhauLayout.setVerticalGroup(
            btn_doimatkhauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_doimatkhauLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(btn_doimatkhauLayout.createSequentialGroup()
                .addGroup(btn_doimatkhauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(btn_doimatkhauLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel4)))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel2.add(btn_doimatkhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, 180, 50));

        btn_dangxuat.setBackground(new java.awt.Color(0, 153, 255));
        btn_dangxuat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_dangxuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_dangxuatMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_dangxuatMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_dangxuatMouseExited(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Đăng Xuất");

        jLabel10.setBackground(new java.awt.Color(102, 102, 102));

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/loggout.png"))); // NOI18N

        javax.swing.GroupLayout btn_dangxuatLayout = new javax.swing.GroupLayout(btn_dangxuat);
        btn_dangxuat.setLayout(btn_dangxuatLayout);
        btn_dangxuatLayout.setHorizontalGroup(
            btn_dangxuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_dangxuatLayout.createSequentialGroup()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addGap(40, 40, 40))
        );
        btn_dangxuatLayout.setVerticalGroup(
            btn_dangxuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(btn_dangxuatLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(btn_dangxuatLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.add(btn_dangxuat, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 570, 180, 50));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 700));

        pnlCard1.setBackground(new java.awt.Color(255, 255, 255));
        pnlCard1.setMinimumSize(new java.awt.Dimension(1070, 680));
        pnlCard1.setLayout(new java.awt.BorderLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/trangchu.jpg"))); // NOI18N
        pnlCard1.add(jLabel1, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout pnlCard3Layout = new javax.swing.GroupLayout(pnlCard3);
        pnlCard3.setLayout(pnlCard3Layout);
        pnlCard3Layout.setHorizontalGroup(
            pnlCard3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlCard1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlCard3Layout.setVerticalGroup(
            pnlCard3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlCard1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(pnlCard3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 1070, 700));

        pnlCard4.setLayout(new java.awt.BorderLayout());
        jPanel1.add(pnlCard4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 1070, 680));

        pnlCard5.setLayout(new java.awt.BorderLayout());
        jPanel1.add(pnlCard5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 1070, 680));

        pnlCard6.setLayout(new java.awt.BorderLayout());
        jPanel1.add(pnlCard6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 1070, 680));

        pnlCard7.setLayout(new java.awt.BorderLayout());
        jPanel1.add(pnlCard7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 1070, 680));

        pnlCard8.setLayout(new java.awt.BorderLayout());
        jPanel1.add(pnlCard8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 1070, 680));

        pnlCard2.setOpaque(false);
        pnlCard2.setLayout(new java.awt.BorderLayout());
        jPanel1.add(pnlCard2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 1070, 680));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_sellMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_sellMouseClicked
        bar(jLabel5);
        showForm(new JPanelBanHang(txt_nhanvien.getText().trim()));
    }//GEN-LAST:event_btn_sellMouseClicked

    private void btn_sellMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_sellMouseEntered
        btn_sell.setBackground(Color.decode("#0063EC"));
    }//GEN-LAST:event_btn_sellMouseEntered

    private void btn_sellMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_sellMouseExited
        btn_sell.setBackground(Color.decode("#0099FF"));
    }//GEN-LAST:event_btn_sellMouseExited

    private void btn_productMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_productMouseClicked
        if (role == 0) {
            JOptionPane.showMessageDialog(this, "Bạn không có quyền vào chức năng này");
            return;
        }
        bar(jLabel8);
        showForm(new JPanelSanPham());
    }//GEN-LAST:event_btn_productMouseClicked

    private void btn_productMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_productMouseEntered
        btn_product.setBackground(Color.decode("#0063EC"));
    }//GEN-LAST:event_btn_productMouseEntered

    private void btn_productMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_productMouseExited
        btn_product.setBackground(Color.decode("#0099FF"));
    }//GEN-LAST:event_btn_productMouseExited

    private void btn_staffMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_staffMouseClicked
        if (role == 0) {
            JOptionPane.showMessageDialog(this, "Bạn không có quyền vào chức năng này");
            return;
        }
        bar(jLabel11);
        showForm(new JPanelNhanVien());
    }//GEN-LAST:event_btn_staffMouseClicked

    private void btn_staffMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_staffMouseEntered
        btn_staff.setBackground(Color.decode("#0063EC"));
    }//GEN-LAST:event_btn_staffMouseEntered

    private void btn_staffMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_staffMouseExited
        btn_staff.setBackground(Color.decode("#0099FF"));
    }//GEN-LAST:event_btn_staffMouseExited

    private void btn_customerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_customerMouseClicked
        bar(jLabel14);
        showForm(new JPanelKhachHang());
    }//GEN-LAST:event_btn_customerMouseClicked

    private void btn_customerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_customerMouseEntered
        btn_customer.setBackground(Color.decode("#0063EC"));
    }//GEN-LAST:event_btn_customerMouseEntered

    private void btn_customerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_customerMouseExited
        btn_customer.setBackground(Color.decode("#0099FF"));
    }//GEN-LAST:event_btn_customerMouseExited

    private void btn_promotionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_promotionMouseClicked
        if (role == 0) {
            JOptionPane.showMessageDialog(this, "Bạn không có quyền vào chức năng này");
            return;
        }
        bar(jLabel21);
        showForm(new JPanelKhuyenMai());
    }//GEN-LAST:event_btn_promotionMouseClicked

    private void btn_promotionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_promotionMouseEntered
        btn_promotion.setBackground(Color.decode("#0063EC"));
    }//GEN-LAST:event_btn_promotionMouseEntered

    private void btn_promotionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_promotionMouseExited
        btn_promotion.setBackground(Color.decode("#0099FF"));
    }//GEN-LAST:event_btn_promotionMouseExited

    private void btn_reportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_reportMouseClicked
        if (role == 0) {
            JOptionPane.showMessageDialog(this, "Bạn không có quyền vào chức năng này");
            return;
        }
        bar(jLabel17);
        showForm(new JPanelDoanhThu());
    }//GEN-LAST:event_btn_reportMouseClicked

    private void btn_reportMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_reportMouseEntered
        btn_report.setBackground(Color.decode("#0063EC"));
    }//GEN-LAST:event_btn_reportMouseEntered

    private void btn_reportMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_reportMouseExited
        btn_report.setBackground(Color.decode("#0099FF"));
    }//GEN-LAST:event_btn_reportMouseExited

    private void btn_receiptMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_receiptMouseClicked
        if (role == 0) {
            JOptionPane.showMessageDialog(this, "Bạn không có quyền vào chức năng này");
            return;
        }
        bar(jLabel15);
        showForm(new JPanelHoaDon());
    }//GEN-LAST:event_btn_receiptMouseClicked

    private void btn_receiptMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_receiptMouseEntered
        btn_receipt.setBackground(Color.decode("#0063EC"));
    }//GEN-LAST:event_btn_receiptMouseEntered

    private void btn_receiptMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_receiptMouseExited
        btn_receipt.setBackground(Color.decode("#0099FF"));
    }//GEN-LAST:event_btn_receiptMouseExited

    private void btn_doimatkhauMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_doimatkhauMouseClicked
        bar(jLabel6);
        DoiMatKhau dmk = new DoiMatKhau(txt_nhanvien.getText().trim());
        dmk.setVisible(true);
    }//GEN-LAST:event_btn_doimatkhauMouseClicked

    private void btn_doimatkhauMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_doimatkhauMouseEntered
        btn_doimatkhau.setBackground(Color.decode("#0063EC"));
    }//GEN-LAST:event_btn_doimatkhauMouseEntered

    private void btn_doimatkhauMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_doimatkhauMouseExited
        btn_doimatkhau.setBackground(Color.decode("#0099FF"));
    }//GEN-LAST:event_btn_doimatkhauMouseExited

    private void btn_dangxuatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_dangxuatMouseClicked
        bar(jLabel10);
        int confirm = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn đăng xuất?", "Confirm", JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            View_DangNhap dangNhap = new View_DangNhap();
            dangNhap.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btn_dangxuatMouseClicked

    private void btn_dangxuatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_dangxuatMouseEntered
        btn_dangxuat.setBackground(Color.decode("#0063EC"));
    }//GEN-LAST:event_btn_dangxuatMouseEntered

    private void btn_dangxuatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_dangxuatMouseExited
        btn_dangxuat.setBackground(Color.decode("#0099FF"));
    }//GEN-LAST:event_btn_dangxuatMouseExited

    public void bar(JLabel lb) {
        jLabel5.setOpaque(false);
        jLabel6.setOpaque(false);
        jLabel8.setOpaque(false);
        jLabel10.setOpaque(false);
        jLabel11.setOpaque(false);
        jLabel14.setOpaque(false);
        jLabel15.setOpaque(false);
        jLabel17.setOpaque(false);
        jLabel21.setOpaque(false);
        lb.setOpaque(true);
        jPanel2.repaint();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btn_customer;
    private javax.swing.JPanel btn_dangxuat;
    private javax.swing.JPanel btn_doimatkhau;
    private javax.swing.JPanel btn_product;
    private javax.swing.JPanel btn_promotion;
    private javax.swing.JPanel btn_receipt;
    private javax.swing.JPanel btn_report;
    private javax.swing.JPanel btn_sell;
    private javax.swing.JPanel btn_staff;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbl_date;
    private javax.swing.JLabel lbl_time;
    private javax.swing.JPanel pnlCard1;
    private javax.swing.JPanel pnlCard2;
    private javax.swing.JPanel pnlCard3;
    private javax.swing.JPanel pnlCard4;
    private javax.swing.JPanel pnlCard5;
    private javax.swing.JPanel pnlCard6;
    private javax.swing.JPanel pnlCard7;
    private javax.swing.JPanel pnlCard8;
    private javax.swing.JLabel txt_nhanvien;
    // End of variables declaration//GEN-END:variables
}
